Repository abhisheks008/ML-Crate, pull requests merged in 2021-12, with the labels that each got.

#29 Character recognition
  Character Recognition/Dataset/README.md
  Character Recognition/Images/accuracy.jpg
  Character Recognition/Images/example.jpg
  Character Recognition/Images/loss.jpg
  Character Recognition/Model/README.md
  Character Recognition/Model/character-recognition.ipynb
  Character Recognition/requirements.txt
Labels: SWOC, Approved :tada:, :full_moon: Medium

#32 Add files via upload
  Height and Weight Prediction/Dataset/heightandweightdataset.xlsx
  Height and Weight Prediction/Images/KNN-RMSE-Vs-K-value.png
  Height and Weight Prediction/Images/R2-scores.png
  Height and Weight Prediction/Images/RMSE.png
  Height and Weight Prediction/Images/scatter-plot.png
  Height and Weight Prediction/Model/README.md
  Height and Weight Prediction/Model/weightpredictionfromheight.ipynb
  Height and Weight Prediction/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#37 Titanic Prediction
  Titanic Prediction/Dataset/Readme.md
  Titanic Prediction/Dataset/test.csv
  Titanic Prediction/Dataset/train.csv
  Titanic Prediction/Images/1.PNG
  Titanic Prediction/Images/10.PNG
  Titanic Prediction/Images/11.PNG
  Titanic Prediction/Images/12.PNG
  Titanic Prediction/Images/2.PNG
  Titanic Prediction/Images/3.PNG
  Titanic Prediction/Images/4.PNG
  Titanic Prediction/Images/5.PNG
  Titanic Prediction/Images/6.PNG
  Titanic Prediction/Images/7.PNG
  Titanic Prediction/Images/8.PNG
  Titanic Prediction/Images/9.PNG
  Titanic Prediction/Images/Readme.md
  Titanic Prediction/Model/README.md
  Titanic Prediction/Model/titanic.ipynb
  Titanic Prediction/requirements.txt
Labels: SWOC 2021, Approved :tada:, :fire: Hard

#38 Pima Indians Diabetes Prediction #36
  Pima Indians Diabetes Prediction/Dataset/dataset.md
  Pima Indians Diabetes Prediction/Images/Outcome_distribution.png
  Pima Indians Diabetes Prediction/Images/correlation_heatmap.png
  Pima Indians Diabetes Prediction/Images/gaussiannaivebayes.png
  Pima Indians Diabetes Prediction/Images/glucose_vs_age.png
  Pima Indians Diabetes Prediction/Images/logisticregression.png
  Pima Indians Diabetes Prediction/Images/piechart.png
  Pima Indians Diabetes Prediction/Images/randomforest.png
  Pima Indians Diabetes Prediction/Images/roc_gaussiannaivebayes.png
  Pima Indians Diabetes Prediction/Images/roc_logisticregression.png
  Pima Indians Diabetes Prediction/Images/roc_randomforest.png
  Pima Indians Diabetes Prediction/Model/README.md
  Pima Indians Diabetes Prediction/Model/pima_indians_diabetes.ipynb
  Pima Indians Diabetes Prediction/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#39 Parkinson's Disease Prediction #11
  Parkinson's Disease Prediction/Dataset/parkinsons.data
  Parkinson's Disease Prediction/Images/accuracies bar chart.png
  Parkinson's Disease Prediction/Images/cv accuracies bar chart.png
  Parkinson's Disease Prediction/Images/error rate vs k value.png
  Parkinson's Disease Prediction/Images/heatmap.png
  Parkinson's Disease Prediction/Images/pairplot.png
  Parkinson's Disease Prediction/Model/README.md
  Parkinson's Disease Prediction/Model/parkinson.ipynb
  Parkinson's Disease Prediction/requirements.txt
Labels: SWOC 2021, Approved :tada:, :fire: Hard

#45 Sentiment analysis of tweets
  Sentimental Analysis of tweets/Dataset/Dataset.csv
  Sentimental Analysis of tweets/Images/WORDCLOUD.png
  Sentimental Analysis of tweets/Model/Readme.md
  Sentimental Analysis of tweets/Model/sentiment analysis using tweets.ipynb
  Sentimental Analysis of tweets/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#57 Breast Cancer Wisconsin (Diagnostic)
  Breast Cancer Wisconsin (Diagnostic)/Dataset/README.md
  Breast Cancer Wisconsin (Diagnostic)/Images/1.PNG
  Breast Cancer Wisconsin (Diagnostic)/Images/10.PNG
  Breast Cancer Wisconsin (Diagnostic)/Images/2.PNG
  Breast Cancer Wisconsin (Diagnostic)/Images/3.PNG
  Breast Cancer Wisconsin (Diagnostic)/Images/4.PNG
  Breast Cancer Wisconsin (Diagnostic)/Images/5.PNG
  Breast Cancer Wisconsin (Diagnostic)/Images/6.PNG
  Breast Cancer Wisconsin (Diagnostic)/Images/7.PNG
  Breast Cancer Wisconsin (Diagnostic)/Images/8.PNG
  Breast Cancer Wisconsin (Diagnostic)/Images/9.PNG
  Breast Cancer Wisconsin (Diagnostic)/Model/README.md
  Breast Cancer Wisconsin (Diagnostic)/Model/brest cancer.ipynb
  Breast Cancer Wisconsin (Diagnostic)/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#58 Restaurant Review Classification #18
  Restaurant Review Classification/Dataset/README.md
  Restaurant Review Classification/Images/Correlation.png
  Restaurant Review Classification/Images/Model_accuracy.png
  Restaurant Review Classification/Images/density_plot.png
  Restaurant Review Classification/Images/scatter_plot.png
  Restaurant Review Classification/Model/README.md
  Restaurant Review Classification/Model/Restaurant_Review_Classifier.ipynb
  Restaurant Review Classification/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#63 Heart Disease Prediction
  Heart Disease Prediction/Dataset/Heart_Disease_Prediction.csv
  Heart Disease Prediction/Images/EKG-results-count.png
  Heart Disease Prediction/Images/FBS-over-120-count.png
  Heart Disease Prediction/Images/ST-depression-bar.png
  Heart Disease Prediction/Images/accuracies.png
  Heart Disease Prediction/Images/age-distribution.png
  Heart Disease Prediction/Images/bp-bar.png
  Heart Disease Prediction/Images/chest-pain-type-count.png
  Heart Disease Prediction/Images/cholestrol-bar.png
  Heart Disease Prediction/Images/correlation-matrix.png
  Heart Disease Prediction/Images/error-vs-k-value.png
  Heart Disease Prediction/Images/exercise-angina-count.png
  Heart Disease Prediction/Images/max-HR-ba.png
  Heart Disease Prediction/Images/number-of-vessels-fluro-count.png
  Heart Disease Prediction/Images/rfc-classification-report.png
  Heart Disease Prediction/Images/rfc-confusion-matrix.png
  Heart Disease Prediction/Images/sex-count.png
  Heart Disease Prediction/Images/slope-of-ST-count.png
  Heart Disease Prediction/Images/thallium-count.png
  Heart Disease Prediction/Models/README.md
  Heart Disease Prediction/Models/heart-disease-prediction.ipynb
  Heart Disease Prediction/requirements.txt
Labels: SWOC 2021, Review Ongoing :receipt:

#62 Years of experience and Salary dataset
  Years of experience and Salary dataset/Dataset/README.md
  Years of experience and Salary dataset/Images/README.md
  Years of experience and Salary dataset/Model/README.md
  Years of experience and Salary dataset/Model/Salary_Prediction.ipynb
  Years of experience and Salary dataset/README.md
  Years of experience and Salary dataset/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium
