Repository abhisheks008/ML-Crate, pull requests merged in 2022-01, with the labels that each got.

#64 Banknote Dataset
  Banknote Dataset/Dataset/README.md
  Banknote Dataset/Images/model_accuracy.jpg
  Banknote Dataset/Model/README.md
  Banknote Dataset/Model/eda-banknote-dataset.ipynb
  Banknote Dataset/Model/ml-models-banknote-dataset.ipynb
  Banknote Dataset/requirements.txt
Labels: SWOC 2021, Approved :tada:, :fire: Hard

#68 GTSRB (German traffic sign recognition benchmark) Dataset #53
  GTSRB (German traffic sign recognition benchmark) Dataset/Dataset/README.md
  GTSRB (German traffic sign recognition benchmark) Dataset/Images/Model_accuracy.png
  GTSRB (German traffic sign recognition benchmark) Dataset/Images/No_of_images_distribution.png
  GTSRB (German traffic sign recognition benchmark) Dataset/Model/German_traffic_sign_classifier.ipynb
  GTSRB (German traffic sign recognition benchmark) Dataset/Model/README.md
  GTSRB (German traffic sign recognition benchmark) Dataset/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#69 Student Performance in exam
  Student Performance in Exam/Dataset/ReadMe.md
  Student Performance in Exam/Dataset/StudentsPerformance.csv
  Student Performance in Exam/Images/ReadMe.md
  Student Performance in Exam/Model/ReadMe.md
  Student Performance in Exam/Model/Students_Performance_in_Exams.ipynb
  Student Performance in Exam/ReadMe.md
  Student Performance in Exam/requitements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#70 Swedish Auto Insurance
  Swedish Auto Insurance/Dataset/ReadMe.md
  Swedish Auto Insurance/Dataset/insurance.csv
  Swedish Auto Insurance/Images/ReadMe.md
  Swedish Auto Insurance/Model/ReadMe.md
  Swedish Auto Insurance/Model/Swedish_Auto_Insurance.ipynb
  Swedish Auto Insurance/ReadMe.md
  Swedish Auto Insurance/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#71 Avocado Prices
  Avocado Prices/Dataset/Filtered_dataset.csv
  Avocado Prices/Dataset/README.md
  Avocado Prices/Images/model_accuracy.jpg
  Avocado Prices/Model/README.md
  Avocado Prices/Model/baseline-mode-avacado-prices.ipynb
  Avocado Prices/Model/eda-avocado-prices.ipynb
  Avocado Prices/Model/xgboost-tuning-avocado-gpu.ipynb
  Avocado Prices/requirements.txt
Labels: SWOC 2021, Approved :tada:, :fire: Hard

#76 Solved #72 : IPL Winning Match Predictor Added
  IPL Winning Match Prediction/Dataset/matches.csv
  IPL Winning Match Prediction/Images/player of match.png
  IPL Winning Match Prediction/Images/umpire.png
  IPL Winning Match Prediction/Images/venue.png
  IPL Winning Match Prediction/Model/IPL Winning Match Prediction.ipynb
  IPL Winning Match Prediction/Model/README.md
  IPL Winning Match Prediction/requirements.txt
Labels: SWOC 2021, Approved :tada:, :fire: Hard

#83 Uber Analysis
  Uber Pickup Analysis/Dataset/Readme.md
  Uber Pickup Analysis/Images/Journey by Dispatch Base.PNG
  Uber Pickup Analysis/Images/Journey by hour.PNG
  Uber Pickup Analysis/Images/Journey by month.PNG
  Uber Pickup Analysis/Images/Journey by week day.PNG
  Uber Pickup Analysis/Images/Visualization on Newyork Map.PNG
  Uber Pickup Analysis/Model/Readme.md
  Uber Pickup Analysis/Model/Uber Pick up Analysis.ipynb
  Uber Pickup Analysis/requirements.txt
Labels: SWOC 2021, Approved :tada:, :seedling: Easy

#84 Crypto Currency Price Prediction
  Crypto Currency Price Prediction/Dataset/ReadMe.md
  Crypto Currency Price Prediction/Dataset/coin_Bitcoin.csv
  Crypto Currency Price Prediction/Images/ReadMe.md
  Crypto Currency Price Prediction/Model/Crypto_Currency_Price_Prediction.ipynb
  Crypto Currency Price Prediction/Model/ReadMe.md
  Crypto Currency Price Prediction/ReadMe.md
  Crypto Currency Price Prediction/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium, Points Added

#85 Add files via upload
  House-Price-Prediction/Dataset/USA_Housing.csv
  House-Price-Prediction/Images/linear-regression-model.jpg
  House-Price-Prediction/Model/Linear Regression Model.ipynb
  House-Price-Prediction/Model/Readme.md.docx
  House-Price-Prediction/Model/~$adme.md.docx
  House-Price-Prediction/Requirements/Requirements.txt
Labels: SWOC 2021, Approved :tada:, :seedling: Easy

#86 Solved #73 : Vehicle Insurance Claim Fraud Detection
  Vehicle Insurance Claim Fraud Detection/Dataset/fraud_oracle.csv
  Vehicle Insurance Claim Fraud Detection/Images/newplot (1).png
  Vehicle Insurance Claim Fraud Detection/Images/newplot (2).png
  Vehicle Insurance Claim Fraud Detection/Images/newplot (3).png
  Vehicle Insurance Claim Fraud Detection/Images/newplot.png
  Vehicle Insurance Claim Fraud Detection/Model/README.md
  Vehicle Insurance Claim Fraud Detection/Model/Vehicle Insurance Claim Fraud Detection.ipynb
  Vehicle Insurance Claim Fraud Detection/README.md
  Vehicle Insurance Claim Fraud Detection/requirements.txt
Labels: SWOC 2021, Approved :tada:, :fire: Hard

#87 Mall Customers Segmentation
  Mall Customers Segmentation/Dataset/Mall_Customers.csv
  Mall Customers Segmentation/Dataset/ReadMe.md
  Mall Customers Segmentation/Images/ReadMe.md
  Mall Customers Segmentation/Model/Mall_Customer_Segmentation.ipynb
  Mall Customers Segmentation/Model/ReadMe.md
  Mall Customers Segmentation/ReadMe.md
  Mall Customers Segmentation/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#101 Body Fat Prediction
  Body Fat Prediction/Dataset/ReadMe.md
  Body Fat Prediction/Dataset/bodyfat.csv
  Body Fat Prediction/Images/ReadMe.md
  Body Fat Prediction/Model/Body_Fat_Prediction.ipynb
  Body Fat Prediction/ReadMe.md
  Body Fat Prediction/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#103 added python file and updated readme
  Air Quality Prediction/Dataset/README.md
  Air Quality Prediction/Images/Satisfaction_level_of_people_post_covid.jpg
  Air Quality Prediction/Images/Satisfaction_level_of_people_pre_covid.jpg
  Air Quality Prediction/Images/most_polluted_cities_post_covid.jpg
  Air Quality Prediction/Images/most_polluted_cities_pre_covid.jpg
  Air Quality Prediction/Model/README.md
  Air Quality Prediction/Model/air-quality-eda-and-classification.ipynb
  Air Quality Prediction/requirements.txt
Labels: SWOC 2021, Approved :tada:, :fire: Hard

#102 Big Mart Sales Prediction
  Big Mart Sales Prediction/Dataset/ReadMe.md
  Big Mart Sales Prediction/Dataset/Test.csv
  Big Mart Sales Prediction/Dataset/Train.csv
  Big Mart Sales Prediction/Images/ReadMe.md
  Big Mart Sales Prediction/Model/Big_Mart_Sales_prediction.ipynb
  Big Mart Sales Prediction/Model/ReadMe.md
  Big Mart Sales Prediction/ReadMe.md
  Big Mart Sales Prediction/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium
