Repository abhisheks008/ML-Crate, pull requests merged in 2022-02, with the labels that each got.

#97 Stress Detection
  Stress Detection/Dataset/README.md
  Stress Detection/Dataset/Stress Detection.csv
  Stress Detection/Model/Stress_Detection.ipynb
  Stress Detection/README.md
  Stress Detection/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#135 Stress Detection (Plots Updated)
  Stress Detection/Images/README.md
  Stress Detection/Model/Stress_Detection.ipynb
  Stress Detection/README.md
Labels: enhancement, SWOC 2021

#136 Bitcoin Price Prediction
  Bitcoin Price Prediction/Dataset/README.md
  Bitcoin Price Prediction/Dataset/bitcoin_dataset.csv
  Bitcoin Price Prediction/Images/image1.png
  Bitcoin Price Prediction/Images/image2.png
  Bitcoin Price Prediction/Images/image4.png
  Bitcoin Price Prediction/Images/image5.png
  Bitcoin Price Prediction/Images/images3.png
  Bitcoin Price Prediction/Model/Bitcoin_Price_Prediction.ipynb
  Bitcoin Price Prediction/Model/README.md
  Bitcoin Price Prediction/README.md
  Bitcoin Price Prediction/requirements.txt
Labels: Approved :tada:, medium, JWOC

#163 Uk favourite chocolate analysis
  UK Favourite Chocolate Analysis/Dataset/Top 10 Chocolate Bars.csv
  UK Favourite Chocolate Analysis/Images/age_group_18_24.png
  UK Favourite Chocolate Analysis/Images/age_group_35_44.png
  UK Favourite Chocolate Analysis/Images/age_group_above_65.png
  UK Favourite Chocolate Analysis/Model/Readme.md
  UK Favourite Chocolate Analysis/Model/UK Favourite Chocolate Analysis.ipynb
  UK Favourite Chocolate Analysis/requirements.txt
Labels: Approved :tada:, easy, JWOC

#164 Advertisement Click Prediction
  Advertisement Click Prediction/Dataset/README.md
  Advertisement Click Prediction/Dataset/Social_Network_Ads.csv
  Advertisement Click Prediction/Images/accuracy.png
  Advertisement Click Prediction/Images/age-purchased.png
  Advertisement Click Prediction/Images/box-purchased-age.png
  Advertisement Click Prediction/Images/box-purchased-salary.png
  Advertisement Click Prediction/Images/correlation.png
  Advertisement Click Prediction/Images/gender.png
  Advertisement Click Prediction/Images/purchased-gender.png
  Advertisement Click Prediction/Images/purchased.png
  Advertisement Click Prediction/Images/salary-purchased.png
  Advertisement Click Prediction/Model/README.md
  Advertisement Click Prediction/Model/advertisement_click_prediction.ipynb
  Advertisement Click Prediction/requirements.txt
Labels: Requested Changes :gear:, JWOC

#171 FLICKR8k Dataset Analysis (MS COCO)
  FLICKR8k Dataset Analysis (MS COCO)/Dataset/Flickr8k.token.txt
  FLICKR8k Dataset Analysis (MS COCO)/Dataset/Flickr_8k.testImages.txt
  FLICKR8k Dataset Analysis (MS COCO)/Dataset/Flickr_8k.trainImages.txt
  FLICKR8k Dataset Analysis (MS COCO)/Images/image1.png
  FLICKR8k Dataset Analysis (MS COCO)/Images/image2.png
  FLICKR8k Dataset Analysis (MS COCO)/Images/image3.png
  FLICKR8k Dataset Analysis (MS COCO)/Images/image4.png
  FLICKR8k Dataset Analysis (MS COCO)/Images/image5.png
  FLICKR8k Dataset Analysis (MS COCO)/Images/image6.png
  FLICKR8k Dataset Analysis (MS COCO)/Model/Image Caption Generator.ipynb
  FLICKR8k Dataset Analysis (MS COCO)/Model/README.md
  FLICKR8k Dataset Analysis (MS COCO)/requirements.txt
Labels: SWOC 2021, Approved :tada:, :fire: Hard

#172 US_Household_Income_Analysis
  US Household Income Distribution Analysis/Dataset/Household Income Distribution by State.csv
  US Household Income Distribution Analysis/Dataset/README.md
  US Household Income Distribution Analysis/Images/NumberofHouseholds.png
  US Household Income Distribution Analysis/Images/PerccentofTotal.png
  US Household Income Distribution Analysis/Images/Scattter.png
  US Household Income Distribution Analysis/Images/correlation.png
  US Household Income Distribution Analysis/Images/distribution.png
  US Household Income Distribution Analysis/Images/pairplot.png
  US Household Income Distribution Analysis/Images/year.png
  US Household Income Distribution Analysis/Model/README.md
  US Household Income Distribution Analysis/Model/US_Household_Income_Analysis.ipynb
  US Household Income Distribution Analysis/Requirements.txt
Labels: Approved :tada:, easy, JWOC

#173 Engineering Placements Prediction
  Engineering Placements Prediction/Dataset/README.md
  Engineering Placements Prediction/Dataset/collegePlace.csv
  Engineering Placements Prediction/Images/image1.png
  Engineering Placements Prediction/Images/image10.png
  Engineering Placements Prediction/Images/image2.png
  Engineering Placements Prediction/Images/image3.png
  Engineering Placements Prediction/Images/image4.png
  Engineering Placements Prediction/Images/image5.png
  Engineering Placements Prediction/Images/image6.png
  Engineering Placements Prediction/Images/image7.png
  Engineering Placements Prediction/Images/image8.png
  Engineering Placements Prediction/Images/image9.png
  Engineering Placements Prediction/Model/Engineering_Placements_Prediction.ipynb
  Engineering Placements Prediction/Model/README.md
  Engineering Placements Prediction/requirements.txt
Labels: Approved :tada:, medium, JWOC

#175 Added Digit Recognizer Project
  Digit Recognizer Project/Dataset/README.md
  Digit Recognizer Project/Model/README.md
  Digit Recognizer Project/Model/mnist.ipynb
  Digit Recognizer Project/images/count.png
  Digit Recognizer Project/images/cover.png
  Digit Recognizer Project/images/dataset.png
  Digit Recognizer Project/images/output-model_2.png
  Digit Recognizer Project/requirements.txt
Labels: Requested Changes :gear:, JWOC

#190 Concrete Strength Calculation
  Concrete Strength Calculation/Dataset/README.md
  Concrete Strength Calculation/Images/distribution_for_each_variable.jpg
  Concrete Strength Calculation/Images/model_accuracy.jpg
  Concrete Strength Calculation/Model/README.md
  Concrete Strength Calculation/Model/baseline-models-concrete-strength-regression.ipynb
  Concrete Strength Calculation/Model/eda-concrete-strength.ipynb
  Concrete Strength Calculation/Model/xgboost-tuning-concrete-strength-gpu.ipynb
  Concrete Strength Calculation/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#192 Indian School Education Statistics #159
  Indian School Education Statistics/Dataset/README.md
  Indian School Education Statistics/Dataset/dropout-ratio-2012-2015.csv
  Indian School Education Statistics/Dataset/gross-enrollment-ratio-2013-2016.csv
  Indian School Education Statistics/Dataset/percentage-of-schools-with-comps-2013-2016.csv
  Indian School Education Statistics/Dataset/percentage-of-schools-with-electricity-2013-2016.csv
  Indian School Education Statistics/Dataset/percentage-of-schools-with-water-facility-2013-2016.csv
  Indian School Education Statistics/Dataset/schools-with-boys-toilet-2013-2016.csv
  Indian School Education Statistics/Dataset/schools-with-girls-toilet-2013-2016.csv
  Indian School Education Statistics/Images/boys_rajastan.png
  Indian School Education Statistics/Images/comp-tn.png
  Indian School Education Statistics/Images/comp_bar_plot
  Indian School Education Statistics/Images/dropout_corr.png
  Indian School Education Statistics/Images/elec_andhra.png
  Indian School Education Statistics/Images/girls_tripura.png
  Indian School Education Statistics/Images/gross_hist.png
  Indian School Education Statistics/Images/gross_pair.png
  Indian School Education Statistics/Images/pie_chart
  Indian School Education Statistics/Images/water_bar_plot
  Indian School Education Statistics/Images/water_kerala.png
  Indian School Education Statistics/Model/Indian_School_Education_Statistics.ipynb
  Indian School Education Statistics/Model/README.md
  Indian School Education Statistics/requirements.txt
Labels: Approved :tada:, medium, JWOC

#191 Ethereum Fraud Detection
  Ethereum Fraud Detection/Dataset/README.md
  Ethereum Fraud Detection/Dataset/transaction_dataset.csv
  Ethereum Fraud Detection/Images/SentTns-UniqueSentToAddress.png
  Ethereum Fraud Detection/Images/UniqueSentAddress-SentTnx.png
  Ethereum Fraud Detection/Images/confusion matrix.png
  Ethereum Fraud Detection/Images/correlation.png
  Ethereum Fraud Detection/Images/flag.png
  Ethereum Fraud Detection/Images/missingvalues.png
  Ethereum Fraud Detection/Images/totalTransactions-ReceivedTnx.png
  Ethereum Fraud Detection/Images/unique_ReceivedFromAddess-ReceivedTnx.png
  Ethereum Fraud Detection/Model/Ethereum_Fraud_Detection.ipynb
  Ethereum Fraud Detection/Model/README.md
  Ethereum Fraud Detection/Requirements.txt
Labels: Approved :tada:, medium, JWOC

#193 Real / Fake Job Posting Prediction
  Real Fake Job Posting Prediction/Dataset/README.md
  Real Fake Job Posting Prediction/Model/README.md
  Real Fake Job Posting Prediction/Model/job-detector.ipynb
  Real Fake Job Posting Prediction/images/confusion-1.png
  Real Fake Job Posting Prediction/images/confusion-2.png
  Real Fake Job Posting Prediction/images/confusion-3.png
  Real Fake Job Posting Prediction/images/confusion-4.png
  Real Fake Job Posting Prediction/images/count-1.png
  Real Fake Job Posting Prediction/images/count-2.png
  Real Fake Job Posting Prediction/images/cover.png
  Real Fake Job Posting Prediction/images/tree.png
  Real Fake Job Posting Prediction/requirements.txt
Labels: Approved :tada:, medium, JWOC

#195 Eye Disease Prediction
  Eye Disease Prediction/Dataset/README.md
  Eye Disease Prediction/Images/image1.png
  Eye Disease Prediction/Images/image2.PNG
  Eye Disease Prediction/Images/image3.png
  Eye Disease Prediction/Model/Eye_Disease_Detection.ipynb
  Eye Disease Prediction/Model/README.md
  Eye Disease Prediction/requirements.txt
Labels: Approved :tada:, hard, JWOC

#197 Cat and dog image classification
  Identify the images of Cats and dogs/Images/cat.1.jpg
  Identify the images of Cats and dogs/Images/cat.10.jpg
  Identify the images of Cats and dogs/Images/cat.11.jpg
  Identify the images of Cats and dogs/Images/cat.12.jpg
  Identify the images of Cats and dogs/Images/cat.13.jpg
  Identify the images of Cats and dogs/Images/cat.14.jpg
  Identify the images of Cats and dogs/Images/cat.2.jpg
  Identify the images of Cats and dogs/Images/cat.3.jpg
  Identify the images of Cats and dogs/Images/cat.4.jpg
  Identify the images of Cats and dogs/Images/cat.5.jpg
  Identify the images of Cats and dogs/Images/cat.6.jpg
  Identify the images of Cats and dogs/Images/cat.7.jpg
  Identify the images of Cats and dogs/Images/cat.8.jpg
  Identify the images of Cats and dogs/Images/cat.9.jpg
  Identify the images of Cats and dogs/Images/dog.1.jpg
  Identify the images of Cats and dogs/Images/dog.10.jpg
  Identify the images of Cats and dogs/Images/dog.11.jpg
  Identify the images of Cats and dogs/Images/dog.12.jpg
  Identify the images of Cats and dogs/Images/dog.13.jpg
  Identify the images of Cats and dogs/Images/dog.14.jpg
  Identify the images of Cats and dogs/Images/dog.2.jpg
  Identify the images of Cats and dogs/Images/dog.3.jpg
  Identify the images of Cats and dogs/Images/dog.4.jpg
  Identify the images of Cats and dogs/Images/dog.5.jpg
  Identify the images of Cats and dogs/Images/dog.6.jpg
  Identify the images of Cats and dogs/Images/dog.7.jpg
  Identify the images of Cats and dogs/Images/dog.8.jpg
  Identify the images of Cats and dogs/Images/dog.9.jpg
  Identify the images of Cats and dogs/Models/README.md
  Identify the images of Cats and dogs/Models/dog_cat_image_classification.ipynb
  Identify the images of Cats and dogs/dataset/README.md
  Identify the images of Cats and dogs/requirements.txt
Labels: Approved :tada:, hard, JWOC

#174 Enron Email Dataset
  Enron Email Dataset/Dataset/Readme.md
  Enron Email Dataset/Images/Capture 1.PNG
  Enron Email Dataset/Images/Capture.PNG
  Enron Email Dataset/Model/Enron.ipynb
  Enron Email Dataset/Model/Readme.md
  Enron Email Dataset/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#200 Netflix Movies and TV Shows
  Netflix Movies and TV Shows/Dataset/README.md
  Netflix Movies and TV Shows/Images/20_contries_with_most_content.jpg
  Netflix Movies and TV Shows/Images/content_added_over_the_years.jpg
  Netflix Movies and TV Shows/Images/distribution_of_movie_rating.jpg
  Netflix Movies and TV Shows/Images/types_of_netflix-content.jpg
  Netflix Movies and TV Shows/Model/README.md
  Netflix Movies and TV Shows/Model/netflix-movies-and-tv-shows-eda.ipynb
  Netflix Movies and TV Shows/requirements.txt
Labels: SWOC 2021, Approved :tada:, :fire: Hard

#201 Bpl analysis
  Bangladesh Premier League Analysis/Dataset/Readme.md
  Bangladesh Premier League Analysis/Dataset/batsman.csv
  Bangladesh Premier League Analysis/Dataset/bowler.csv
  Bangladesh Premier League Analysis/Dataset/bpl.csv
  Bangladesh Premier League Analysis/Images/Most_MOM_awards.png
  Bangladesh Premier League Analysis/Images/Most_fours.png
  Bangladesh Premier League Analysis/Images/Most_runs.png
  Bangladesh Premier League Analysis/Images/Most_sixes.png
  Bangladesh Premier League Analysis/Images/Most_time_toss_winners.png
  Bangladesh Premier League Analysis/Images/Most_time_umpire1.png
  Bangladesh Premier League Analysis/Images/Most_time_umpire_2.png
  Bangladesh Premier League Analysis/Images/Most_wickets.png
  Bangladesh Premier League Analysis/Images/toss_decision.png
  Bangladesh Premier League Analysis/Models/BPL_analysis.ipynb
  Bangladesh Premier League Analysis/Models/Readme.md
  Bangladesh Premier League Analysis/requirements.TXT
Labels: Approved :tada:, medium, JWOC

#202 Top Programming language in GitHub #166
  Top Programming language in GitHub/Dataset/README.md
  Top Programming language in GitHub/Dataset/issues.csv
  Top Programming language in GitHub/Dataset/prs.csv
  Top Programming language in GitHub/Dataset/repos.csv
  Top Programming language in GitHub/Images/issues_year.png
  Top Programming language in GitHub/Images/prs-year.png
  Top Programming language in GitHub/Images/top-issues.png
  Top Programming language in GitHub/Images/top-prs.png
  Top Programming language in GitHub/Images/top_15_repo.png
  Top Programming language in GitHub/Model/README.md
  Top Programming language in GitHub/Model/Top_Programming_language_in_Github.ipynb
  Top Programming language in GitHub/requirements.txt
Labels: Approved :tada:, medium, JWOC

#204 Entrepreneurial Capacity in Student
  Entrepreneurial Capacity in Student/Dataset/Readme.md
  Entrepreneurial Capacity in Student/Dataset/data.csv
  Entrepreneurial Capacity in Student/Images/Education.png
  Entrepreneurial Capacity in Student/Images/Histogram(y).png
  Entrepreneurial Capacity in Student/Images/features.png
  Entrepreneurial Capacity in Student/Model/Entrepreneurial_Capacity_in_Student.ipynb
  Entrepreneurial Capacity in Student/Model/Readme.md
  Entrepreneurial Capacity in Student/Requirements.txt
Labels: Approved :tada:, medium, JWOC

#205 Sonar Dataset #49
  Sonar Dataset/Dataset/README.md
  Sonar Dataset/Images/model_accuracy.jpg
  Sonar Dataset/Model/README.md
  Sonar Dataset/Model/bayesian-opt-and-k-fold-sonar-dataset.ipynb
  Sonar Dataset/Model/comparing-5-models-sonar.ipynb
  Sonar Dataset/Model/eda-sonar-dataset.ipynb
  Sonar Dataset/requirements.txt
Labels: SWOC 2021, Approved :tada:, :fire: Hard

#207 League of Legends Analysis
  League Of Legends Analysis/Dataset/League of Legends Champion Stats 12.1.csv.xls
  League Of Legends Analysis/Model/LOLanalysis.ipynb
  League Of Legends Analysis/Model/Readme.md
  League Of Legends Analysis/images/%class_in_LOL.png
  League Of Legends Analysis/images/%role_in_LOL.png
  League Of Legends Analysis/images/KDA&Winrate.png
  League Of Legends Analysis/images/pickrate_&_winrate.png
  League Of Legends Analysis/requirements.txt
Labels: Approved :tada:, medium, JWOC

#206 Resume Classification
  Air Quality Prediction/requirements.txt
  Resume Classification/Dataset/UpdatedResumeDataSet.csv
  Resume Classification/Images/Categories.png
  Resume Classification/Images/Wordcloud.png
  Resume Classification/Images/model.png
  Resume Classification/Model/README.md
  Resume Classification/Model/ResumeClassification.ipynb
  Resume Classification/requirements.txt
Labels: SWOC 2021, Approved :tada:, :full_moon: Medium

#210 Rihanna lyrics analysis
  Rihanna Lyrics Analysis/Dataset/Readme.md
  Rihanna Lyrics Analysis/Dataset/Rihanna Lyrics.csv
  Rihanna Lyrics Analysis/Images/top_5_albums.png
  Rihanna Lyrics Analysis/Images/top_5_songs.png
  Rihanna Lyrics Analysis/Images/top_5_songs_2005.png
  Rihanna Lyrics Analysis/Images/top_5_songs_2006.png
  Rihanna Lyrics Analysis/Images/top_5_songs_2007.png
  Rihanna Lyrics Analysis/Images/top_5_songs_2009.png
  Rihanna Lyrics Analysis/Images/top_5_songs_2010.png
  Rihanna Lyrics Analysis/Images/top_5_songs_2011.png
  Rihanna Lyrics Analysis/Images/top_5_songs_2012.png
  Rihanna Lyrics Analysis/Images/top_5_songs_2016.png
  Rihanna Lyrics Analysis/Images/top_5_years.png
  Rihanna Lyrics Analysis/Models/Readme.md
  Rihanna Lyrics Analysis/Models/Rihanna_Lyrics_Analysis.ipynb
  Rihanna Lyrics Analysis/requirements.TXT
Labels: Approved :tada:, medium, JWOC

#211 Added Face Mask Detection
  Face Mask Detection/Dataset/README.md
  Face Mask Detection/Images/model-1.png
  Face Mask Detection/Images/output-1.png
  Face Mask Detection/Images/output-2.png
  Face Mask Detection/Model/README.md
  Face Mask Detection/Model/model.ipynb
  Face Mask Detection/requirements.txt
Labels: Approved :tada:, hard, JWOC

#215 Quora
  Quora Insincere Questions Classification Analysis & Prediction/Model/README.md
  Quora Insincere Questions Classification Analysis & Prediction/Model/quora-quetion-classification.ipynb
  Quora Insincere Questions Classification Analysis & Prediction/requirements.txt
Labels: SWOC 2021, Approved :tada:, :seedling: Easy

#214 Brain tumor detection
  Brain Tumor Detection/Dataset/Readme.md
  Brain Tumor Detection/Images/No_Tumor.jpg
  Brain Tumor Detection/Images/Tumor.JPG
  Brain Tumor Detection/Model/Brain_Tumor_detection.ipynb
  Brain Tumor Detection/Model/Readme.md
  Brain Tumor Detection/requirements.TXT
Labels: Approved :tada:, hard, JWOC

#218 Amazon Alexa Reviews #89
  Amazon Alexa Reviews/Dataset/README.md
  Amazon Alexa Reviews/Images/model_accuracy.jpg
  Amazon Alexa Reviews/Images/reviews_per_variation.jpg
  Amazon Alexa Reviews/Model/EDA and Model Training on Alexa Reviews.ipynb
  Amazon Alexa Reviews/Model/README.md
  Amazon Alexa Reviews/requirements.txt
Labels: SWOC 2021, Approved :tada:, :fire: Hard

#217 Body part classification
  Body Parts Recognition/Dataset/Readme.md
  Body Parts Recognition/Images/Elbow_35.jpg
  Body Parts Recognition/Images/Eye_161.jpg
  Body Parts Recognition/Images/Shoulders_176.jpg
  Body Parts Recognition/Model/Body_part_classification.ipynb
  Body Parts Recognition/Model/Readme.md
  Body Parts Recognition/requirements.txt
Labels: Approved :tada:, hard, JWOC

#216 Women's E-commerce Clothings Analysis
  Womens E-Commerce Clothing Review/Dataset/README.md
  Womens E-Commerce Clothing Review/Dataset/Womens Clothing E-Commerce Reviews.csv.zip
  Womens E-Commerce Clothing Review/Images/Class Distribution.png
  Womens E-Commerce Clothing Review/Images/Department.png
  Womens E-Commerce Clothing Review/Images/Division Distribution.png
  Womens E-Commerce Clothing Review/Images/Rating Distribution.png
  Womens E-Commerce Clothing Review/Model/ClothingReview.ipynb
  Womens E-Commerce Clothing Review/Model/README.md
Labels: Approved :tada:, medium, JWOC

#221 Data Analytics Salary Prediction #142
  Data Analytics Salary Prediction/Dataset/README.md
  Data Analytics Salary Prediction/Dataset/Salary Dataset.csv
  Data Analytics Salary Prediction/Images/avdslr_peryear_loc
  Data Analytics Salary Prediction/Images/avgslr_each_job.png
  Data Analytics Salary Prediction/Images/avgslr_location.png
  Data Analytics Salary Prediction/Images/avgslr_top_10_company.png
  Data Analytics Salary Prediction/Images/top_6_high_pay_company
  Data Analytics Salary Prediction/Images/top_6_jobs.png
  Data Analytics Salary Prediction/Images/top_6_less_pay_company
  Data Analytics Salary Prediction/Model/Data Analytics Salary Prediction.ipynb
  Data Analytics Salary Prediction/Model/README.md
  Data Analytics Salary Prediction/requirements.txt
Labels: Approved :tada:, medium, JWOC

#228 Udacity courses analysis
  Udacity Courses Analysis/Dataset/Readme.md
  Udacity Courses Analysis/Images/Advanced_courses.png
  Udacity Courses Analysis/Images/beginner_course.png
  Udacity Courses Analysis/Images/intermediate_courses.png
  Udacity Courses Analysis/Model/Readme.md
  Udacity Courses Analysis/Model/Udacity_courses_analysis.ipynb
  Udacity Courses Analysis/requirements.TXT
Labels: Approved :tada:, medium, JWOC

#229 Rice type classification
  Rice type classification/Dataset/README.md
  Rice type classification/Dataset/riceClassification.csv
  Rice type classification/Images/Class_distribution.png
  Rice type classification/Images/Correlation_heatmap.png
  Rice type classification/Images/Model_accuracy.png
  Rice type classification/Images/ROC_curve.png
  Rice type classification/Model/README.md
  Rice type classification/Model/rice_type_classification.ipynb
  Rice type classification/requirements.txt
Labels: Approved :tada:, medium, JWOC

#230 Named Entity Recognition (NER) Corpus
  Named Entity Recognition (NER) Corpus - Copy/Dataset/Readme.md
  Named Entity Recognition (NER) Corpus - Copy/Images/tags_frequency.png
  Named Entity Recognition (NER) Corpus - Copy/Model/Named_Entity_Recognition_(NER)_Corpus.ipynb
  Named Entity Recognition (NER) Corpus - Copy/Model/Readme.md
  Named Entity Recognition (NER) Corpus - Copy/requirements.txt
Labels: Requested Changes :gear:, JWOC

#232 Lumpy Skin Disease Prediction
  Lumpy Skin Disease Prediction/Dataset/Lumpy skin disease data.csv
  Lumpy Skin Disease Prediction/Dataset/README.md
  Lumpy Skin Disease Prediction/Images/Class_distribution.png
  Lumpy Skin Disease Prediction/Images/Correlation_heatmap.png
  Lumpy Skin Disease Prediction/Images/Model_accuracy.png
  Lumpy Skin Disease Prediction/Images/ROC_curve.png
  Lumpy Skin Disease Prediction/Model/Lumpy_Skin_Disease_Prediction.ipynb
  Lumpy Skin Disease Prediction/Model/README.md
  Lumpy Skin Disease Prediction/requirements.txt
Labels: Approved :tada:, medium, JWOC

#233 Amazon Books Analysis
  Amazon Books Analysis/Dataset/README.md
  Amazon Books Analysis/Images/authorofbestseller.jpg
  Amazon Books Analysis/Images/genre_based_bestseller.jpg
  Amazon Books Analysis/Images/ratingcount.jpg
  Amazon Books Analysis/Model/README.md
  Amazon Books Analysis/Model/amazon-bestselling-books.ipynb
  Amazon Books Analysis/requirements.txt
Labels: SWOC 2021, Approved :tada:, :fire: Hard
