Repository abhisheks008/ML-Crate, pull requests merged in 2022-12, with the labels that each got.

#403 Smartphone Brands Analysis
  Smartphone Brands Analysis/dataset/Amazon_top5_mobilephones.csv
  Smartphone Brands Analysis/images/Apple.png
  Smartphone Brands Analysis/images/BTC.png
  Smartphone Brands Analysis/images/IKALL.png
  Smartphone Brands Analysis/images/Lava.png
  Smartphone Brands Analysis/images/Oppo.png
  Smartphone Brands Analysis/images/Redmi.png
  Smartphone Brands Analysis/images/Samsung.png
  Smartphone Brands Analysis/images/Vivo.png
  Smartphone Brands Analysis/images/Xiaomi .png
  Smartphone Brands Analysis/images/averagecount.png
  Smartphone Brands Analysis/images/brandcount.png
  Smartphone Brands Analysis/images/brandplot.png
  Smartphone Brands Analysis/images/pricecount.png
  Smartphone Brands Analysis/images/ratingcount.png
  Smartphone Brands Analysis/images/reviewcount.png
  Smartphone Brands Analysis/model/.ipynb_checkpoints/model-checkpoint.ipynb
  Smartphone Brands Analysis/model/model.ipynb
  Smartphone Brands Analysis/readme.md
  Smartphone Brands Analysis/requirements.txt
Labels: Approved :white_check_mark:, KWOC 2022

#402 Chocolate Classification and Prediction
  Chocolate Classification and Prediction/Dataset/README.md
  Chocolate Classification and Prediction/Images/plots.png
  Chocolate Classification and Prediction/Images/test1White+2Dark.jpg
  Chocolate Classification and Prediction/Images/testWhitechoco.jpeg
  Chocolate Classification and Prediction/Images/testdarkchoco.jpg
  Chocolate Classification and Prediction/Model/README.md
  Chocolate Classification and Prediction/Model/chocolate_classification_and Prediction_PranjalRkgp_KWOC.ipynb
  Chocolate Classification and Prediction/Requirements.txt
Labels: Requested Changes :gear:

#410 World Crime Rates Analysis
  World Crime Rates Analysis/Dataset/World Crime Index .csv
  World Crime Rates Analysis/Images/histogram plot of number of cities with crime index.png
  World Crime Rates Analysis/Images/top 10 countries with highest crime index.jpg
  World Crime Rates Analysis/Images/top 10 countries with highest safety index.jpg
  World Crime Rates Analysis/Images/top 10 safe cities.jpg
  World Crime Rates Analysis/Images/top 10 unsafe cities.jpg
  World Crime Rates Analysis/Model/README.md
  World Crime Rates Analysis/Model/World Crime Rate Analysis.ipynb
Labels: Approved :white_check_mark:, KWOC 2022

#413 updated the analysis and added competitors analysis
  Uber Pickup Analysis/Model/Uber Pick up Analysis.ipynb
  Uber Pickup Analysis/Model/uber_competitor_analysis.ipynb
Labels: enhancement, Approved :white_check_mark:, KWOC 2022

#415 Hong Kong Rainstorm Record Analysis
  Hong Kong Rainstorm Record Analysis/Dataset/rainstorm.csv
  Hong Kong Rainstorm Record Analysis/Images/output1.png
  Hong Kong Rainstorm Record Analysis/Images/output2.png
  Hong Kong Rainstorm Record Analysis/Images/output3.png
  Hong Kong Rainstorm Record Analysis/Images/output4.png
  Hong Kong Rainstorm Record Analysis/Images/output5.png
  Hong Kong Rainstorm Record Analysis/Model/Hong_Kong_Rainstorm_Record_Analysis.ipynb
  Hong Kong Rainstorm Record Analysis/Model/README.md
  Hong Kong Rainstorm Record Analysis/requirements.txt.txt
Labels: Approved :white_check_mark:, KWOC 2022

#412 Cancer Analysis based on Chernobyl Event
  Cancer Analysis based on Chernobyl Event/Datasets/dataset.csv
  Cancer Analysis based on Chernobyl Event/Images/visualization_image1.png
  Cancer Analysis based on Chernobyl Event/Images/visualization_image2.png
  Cancer Analysis based on Chernobyl Event/Images/visualization_image3.png
  Cancer Analysis based on Chernobyl Event/Images/visualization_image4.png
  Cancer Analysis based on Chernobyl Event/Images/visualization_image5.png
  Cancer Analysis based on Chernobyl Event/Images/visualization_image6.png
  Cancer Analysis based on Chernobyl Event/Images/visualization_image7.png
  Cancer Analysis based on Chernobyl Event/Images/visualization_image8.png
  Cancer Analysis based on Chernobyl Event/Model/README.md
  Cancer Analysis based on Chernobyl Event/Model/cancer_analysis_based_on_Chernobyl_event.ipynb
  Cancer Analysis based on Chernobyl Event/requirements.txt
Labels: Approved :white_check_mark:, KWOC 2022

#416 Update ASELSAN Stock Prices.ipynb
  ASELSAN Stock Prices/Model/ASELSAN Stock Prices.ipynb
Labels: enhancement, Approved :white_check_mark:, KWOC 2022

#425 Soil Moisture Prediction
  Soil Moisture Prediction/Dataset/vase1.CSV
  Soil Moisture Prediction/Dataset/vase2.CSV
  Soil Moisture Prediction/Images/vase1.png
  Soil Moisture Prediction/Images/vase2.png
  Soil Moisture Prediction/Models/README.md
  Soil Moisture Prediction/Models/Soil_Moisture.ipynb
  Soil Moisture Prediction/requirements.txt
Labels: Approved :white_check_mark:, KWOC 2022

#429 Updated uber pickup analysis nyc
  Uber Pickup Analysis/Model/Uber Pick up Analysis.ipynb
Labels: enhancement, KWOC 2022
