Repository abhisheks008/ML-Crate, pull requests merged in 2022-07, with the labels that each got.

#257 Search Interests in Google
  Search Interests in Google/DataSet/README.md
  Search Interests in Google/DataSet/trends_the Kardashians and Jenners..csv
  Search Interests in Google/Images/Screenshot 2022-07-16 at 4.52.59 PM.png
  Search Interests in Google/Images/Screenshot 2022-07-16 at 4.53.10 PM.png
  Search Interests in Google/Images/Screenshot 2022-07-16 at 4.53.18 PM.png
  Search Interests in Google/Images/Screenshot 2022-07-16 at 4.53.26 PM.png
  Search Interests in Google/Images/Screenshot 2022-07-16 at 4.53.32 PM.png
  Search Interests in Google/Images/Screenshot 2022-07-16 at 4.53.39 PM.png
  Search Interests in Google/Model/Search Interests in Google.ipynb
  Search Interests in Google/README.md
Labels: Approved :white_check_mark:, HSOC22-Level-2

#263 Diseases Prediction
  Diseases Prediction/GUI/gui.py
  Diseases Prediction/README.md
  Diseases Prediction/dataset/Prototype.csv
  Diseases Prediction/dataset/Prototype_1.csv
  Diseases Prediction/dataset/dataset_into.md
  Diseases Prediction/images/dd.png
  Diseases Prediction/model/Diseases Prediction.ipynb
Labels: Approved :white_check_mark:, HSOC22-Level-3

#266 Analysis and prediction of power Consumption of States in India
  Power Consumption in India/Dataset/dataset_tk.csv
  Power Consumption in India/Dataset/long_data_.csv
  Power Consumption in India/Images/Andhrapradesh box plot for two year power consumption.png
  Power Consumption in India/Images/Decision Tree Regressor Prediction.png
  Power Consumption in India/Images/Distplot for power consumption in states.png
  Power Consumption in India/Images/Gujarat box plot for two year power consumption.png
  Power Consumption in India/Images/Heatmap of states.png
  Power Consumption in India/Images/Histogram for power consumption for Andhra Pradesh.png
  Power Consumption in India/Images/Karnataka box plot for two year power consumption.png
  Power Consumption in India/Images/Maharashtra box plot for two year power consumption.png
  Power Consumption in India/Model/Power consumption - Piyush.ipynb
  Power Consumption in India/Model/model.pkl
  Power Consumption in India/Readme.md
Labels: Approved :white_check_mark:, HSOC22-Level-2

#268 PUSHING Online Education System
  Online Education System/Dataset/ONLINE EDUCATION SYSTEM REVIEW.csv
  Online Education System/Model/.ipynb_checkpoints/Online Education System-checkpoint.ipynb
  Online Education System/Model/ONLINE EDUCATION SYSTEM REVIEW.csv
  Online Education System/Model/Online Education System.ipynb
  Online Education System/Model/README2.md
  Online Education System/images/179739889-05d3cd8b-9697-4178-9b21-e21933d91d98.png
  Online Education System/images/179739907-a55ccbc9-3253-4f08-a9e4-8caa7b2e757f.png
  Online Education System/images/179739921-8bd4f54f-ff6d-4e18-a75b-7193b6d9d3ec.png
  Online Education System/images/179739940-97cd8556-3ed5-44b9-87d2-d642c5c44a74.png
  Online Education System/images/179739957-b95be60a-6580-4e71-ab63-feb1c27e4156.png
  Online Education System/images/179739968-afba089d-fec1-4f36-a4ab-1bc103b2c74e.png
  Online Education System/requiremnets.txt
Labels: Approved :white_check_mark:, HSOC22-Level-2

#270 China College Entrance Examination Admission
  China College Entrance Examination Admission/DataSet/README.md
  China College Entrance Examination Admission/DataSet/data.csv
  China College Entrance Examination Admission/Images/Amount of participant in College Admission.png
  China College Entrance Examination Admission/Images/College Entrance Examination Year Bar Chart by Admission Amount of Participants.png
  China College Entrance Examination Admission/Images/College Entrance Examination Year by Amount of Admission.png
  China College Entrance Examination Admission/Images/Pie Chart of 1978-1981.png
  China College Entrance Examination Admission/Images/Pie Chart of 2016-2020 .png
  China College Entrance Examination Admission/Images/Plots against Everyone.png
  China College Entrance Examination Admission/Model/Chine College Entrance Examination Admission.ipynb
  China College Entrance Examination Admission/Model/data.csv
  China College Entrance Examination Admission/README.md
Labels: Approved :white_check_mark:, HSOC22-Level-3

#284 Mr Beast YouTube Channel Analysis
  Mr Beast YouTube Channel Analysis/Dataset/MrBeast_youtube_stats.csv
  Mr Beast YouTube Channel Analysis/Images/179957610-5163bcea-211b-4ac9-9174-c99d0fecbfea.png
  Mr Beast YouTube Channel Analysis/Images/179957639-dce926c6-5738-4dc1-ae56-74e7d2ad8207.png
  Mr Beast YouTube Channel Analysis/Images/179957655-c18deaed-af5f-4ccd-ba9d-27dd0c160e72.png
  Mr Beast YouTube Channel Analysis/Images/179957674-d5fef1f7-4f87-4dd4-b571-d199dbdbf07a.png
  Mr Beast YouTube Channel Analysis/Images/179957687-8306f4db-1cee-4c8e-a9b1-1c11734be067.png
  Mr Beast YouTube Channel Analysis/Images/179957704-efc3b3d3-5e66-45f6-a85f-f0963d22195e.png
  Mr Beast YouTube Channel Analysis/Images/179957723-165b4534-638f-483c-8b3b-aa21d3c6952f.png
  Mr Beast YouTube Channel Analysis/Model/Mr Beast YouTube Channel Analysis.ipynb
  Mr Beast YouTube Channel Analysis/Model/MrBeast_youtube_stats.csv
  Mr Beast YouTube Channel Analysis/Model/README.md
  Mr Beast YouTube Channel Analysis/requiremnets.txt
Labels: Approved :white_check_mark:, HSOC22-Level-3

#285 Top YouTube Channels Analysis
  Top YouTube Channels Analysis/Dataset/Top YouTube Channels Data .csv
  Top YouTube Channels Analysis/Images/180012377-f9327d77-3d74-4a6c-9349-fccb096a5d15.png
  Top YouTube Channels Analysis/Images/180012424-3b97f53e-2f00-42dd-88b8-b2d2d32894fd.png
  Top YouTube Channels Analysis/Images/180012461-d28db3af-d19f-46e2-a963-bdb3307d46ff.png
  Top YouTube Channels Analysis/Images/180012487-0ca0f26b-c689-42b3-a664-e71cb3a8043f.png
  Top YouTube Channels Analysis/Images/180012613-5f68552d-7613-4930-b2a6-a6d6173906dc.png
  Top YouTube Channels Analysis/Images/180012645-4a2d3df4-0f4c-4935-b8db-f38f800a16bd.png
  Top YouTube Channels Analysis/Images/180012938-5002eb4b-24a3-4288-a4c3-7e8c79ff0c73.png
  Top YouTube Channels Analysis/Model/README.md
  Top YouTube Channels Analysis/Model/Top YouTube Channels Analysis.ipynb
  Top YouTube Channels Analysis/Model/Top YouTube Channels Data .csv
  Top YouTube Channels Analysis/requiremnets.txt
Labels: Approved :white_check_mark:, HSOC22-Level-2

#286 Machine Learning Users on Github Analysis
  Github ML Users/DataSet/README.md
  Github ML Users/DataSet/ml_git_users.csv
  Github ML Users/Images/Screenshot 2022-07-20 at 9.03.41 PM.png
  Github ML Users/Images/Screenshot 2022-07-20 at 9.23.17 PM.png
  Github ML Users/Images/Screenshot 2022-07-20 at 9.23.29 PM.png
  Github ML Users/Model/Machine Learning Users on Github Analysis.ipynb
  Github ML Users/Model/ml_git_users.csv
  Github ML Users/README.md
Labels: Approved :white_check_mark:, HSOC22-Level-2

#288 Nobel Prize Analysis File
  Nobel Prize Analysis/Dataset/nobel_final.csv
  Nobel Prize Analysis/Images/180046166-5d903814-7e75-4cf5-956a-5c1497dfdc85.png
  Nobel Prize Analysis/Images/180046177-3ffcbccf-83b6-4d7a-8daf-e83cb6299256.png
  Nobel Prize Analysis/Images/180046190-0529b891-9c32-442e-8c17-653539959487.png
  Nobel Prize Analysis/Images/180046206-3e50b45e-ee8a-4d3b-9f55-fdd0d0978b8c.png
  Nobel Prize Analysis/Images/180046213-0d38be16-73db-47c0-987f-ad4ac2c3d80a.png
  Nobel Prize Analysis/Images/180046222-2eeafeed-5a98-4158-a948-12bd9446d2b8.png
  Nobel Prize Analysis/Images/180046239-82e8d638-4914-4c0c-9fab-57df1e8c2125.png
  Nobel Prize Analysis/Images/180046374-dad23158-a30c-4820-9fe6-d88ab741bd78.png
  Nobel Prize Analysis/Images/180046391-fdc02507-d024-4a61-9060-18585cbf585c.png
  Nobel Prize Analysis/Model/Nobel Prize Analysis.ipynb
  Nobel Prize Analysis/Model/README.md
  Nobel Prize Analysis/Model/nobel_final.csv
  Nobel Prize Analysis/requiremnets.txt
Labels: Approved :white_check_mark:, HSOC22-Level-2

#290 Chennai Zomato Analysis File
  Chennai Zomato Analysis/Dataset/Zomato Chennai Listing 2020.csv
  Chennai Zomato Analysis/Images/180169530-6705f926-03e7-4f2f-ac4b-ff3ef8910f7a.png
  Chennai Zomato Analysis/Images/180169565-0f28a9c6-45a2-4003-b792-7ad7c0c34810.png
  Chennai Zomato Analysis/Images/180169584-279350e1-8c55-4d3a-8322-f56c0c6677a6.png
  Chennai Zomato Analysis/Images/180169638-2289e617-705c-48a0-9343-01157bee0fb4.png
  Chennai Zomato Analysis/Images/180169657-fa4d6b4d-54d2-43ee-a67d-00f1b050dd4b.png
  Chennai Zomato Analysis/Images/180169672-f86b4574-2fb7-448b-93f0-afbc96e73778.png
  Chennai Zomato Analysis/Images/180169685-ff305d63-c9a9-4be3-873f-3f99352912a1.png
  Chennai Zomato Analysis/Images/180169699-2f423b91-1bcd-4ffc-9292-3c021ae238aa.png
  Chennai Zomato Analysis/Images/180169708-1fabb899-e1d1-4379-9f7b-afc62a2ed648.png
  Chennai Zomato Analysis/Model/Chennai Zomato Analysis.ipynb
  Chennai Zomato Analysis/Model/README.md
  Chennai Zomato Analysis/Model/Zomato Chennai Listing 2020.csv
  Chennai Zomato Analysis/requiremnets.txt
Labels: Approved :white_check_mark:, HSOC22-Level-2

#292 Instagram Influencers Analysis File
  Instagram Influencers Analysis/Dataset/top_1000_instagrammers.csv
  Instagram Influencers Analysis/Images/180224423-06a4d984-6c76-448e-bccd-dfb343d8c6e5.png
  Instagram Influencers Analysis/Images/180224509-691d6232-993d-41b2-9732-5aa66e12761a.png
  Instagram Influencers Analysis/Images/180224541-05cd63a9-dcee-4b07-8638-a93bd3e3d9e3.png
  Instagram Influencers Analysis/Images/180224575-02a545a5-6e5e-4dfe-82e8-3e51824e25a2.png
  Instagram Influencers Analysis/Images/180224588-acfc8c60-1f93-410e-b8f7-a96bf30fe07d.png
  Instagram Influencers Analysis/Images/180224599-6b19d526-ac2e-4194-9940-3436157aac2a.png
  Instagram Influencers Analysis/Images/180224612-7c106e63-e018-4583-a5ad-c14132bc38f4.png
  Instagram Influencers Analysis/Model/Instagram Influencers Analysis.ipynb
  Instagram Influencers Analysis/Model/README.md
  Instagram Influencers Analysis/Model/top_1000_instagrammers.csv
  Instagram Influencers Analysis/requiremnets.txt
Labels: Approved :white_check_mark:, HSOC22-Level-2

#299 Guardian League Tables Analysis File
  Guardian League Tables Analysis/Dataset/glt.csv
  Guardian League Tables Analysis/Images/180255013-f5d208bf-69ef-4232-8fc2-2603a5083273.png
  Guardian League Tables Analysis/Images/180255046-97a8dee2-1b24-4550-986d-fd4120925405.png
  Guardian League Tables Analysis/Images/180255064-a84eda15-edd4-4a22-b97e-ead640ce313e.png
  Guardian League Tables Analysis/Images/180255084-389f5906-b1bf-4656-8dcd-c08547391bed.png
  Guardian League Tables Analysis/Images/180255103-afa7ae43-9f9e-4553-a4ad-69e84310bb1a.png
  Guardian League Tables Analysis/Images/180255132-f63f09bf-7bcb-47b3-b581-9cacbbdd807c.png
  Guardian League Tables Analysis/Images/180255177-5a50f813-4d43-4183-a56a-2438982a1326.png
  Guardian League Tables Analysis/Images/180255193-8767a6d6-58e3-4293-b1ed-12f5cf3fb284.png
  Guardian League Tables Analysis/Images/180255210-e391ef22-22a7-42bd-9ec1-722aa1be11e9.png
  Guardian League Tables Analysis/Images/180255226-b84188c9-9c03-4cc0-a76e-1e4f7fb1c2ca.png
  Guardian League Tables Analysis/Images/180255237-6a7e57ea-195d-4fa3-8efa-dcb4160bd331.png
  Guardian League Tables Analysis/Model/Guardian League Tables Analysis.ipynb
  Guardian League Tables Analysis/Model/README11.md
  Guardian League Tables Analysis/Model/glt.csv
  Guardian League Tables Analysis/requiremnets.txt
Labels: Approved :white_check_mark:, HSOC22-Level-2

#300 Top Crypto Currencies Analysis and Prediction
  CryptoCurrency Analysis and Prediction/DataSet/README.md
  CryptoCurrency Analysis and Prediction/DataSet/data.csv
  CryptoCurrency Analysis and Prediction/Images/Screenshot 2022-07-21 at 10.14.16 PM.png
  CryptoCurrency Analysis and Prediction/Images/Screenshot 2022-07-21 at 10.14.27 PM.png
  CryptoCurrency Analysis and Prediction/Images/Screenshot 2022-07-21 at 10.14.44 PM.png
  CryptoCurrency Analysis and Prediction/Images/Screenshot 2022-07-21 at 10.14.53 PM.png
  CryptoCurrency Analysis and Prediction/Images/Screenshot 2022-07-21 at 10.15.01 PM.png
  CryptoCurrency Analysis and Prediction/Images/Screenshot 2022-07-21 at 10.15.07 PM.png
  CryptoCurrency Analysis and Prediction/Images/Screenshot 2022-07-21 at 10.15.13 PM.png
  CryptoCurrency Analysis and Prediction/Images/Screenshot 2022-07-21 at 10.15.20 PM.png
  CryptoCurrency Analysis and Prediction/Images/Screenshot 2022-07-21 at 10.15.30 PM.png
  CryptoCurrency Analysis and Prediction/Images/Screenshot 2022-07-21 at 10.15.39 PM.png
  CryptoCurrency Analysis and Prediction/Model/Top Cryptocurrency Analysis and Prediction.ipynb
  CryptoCurrency Analysis and Prediction/Model/data.csv
  CryptoCurrency Analysis and Prediction/README.md
Labels: Approved :white_check_mark:, HSOC22-Level-3

#301 Mobile Price Classification File
  Mobile Price Classification/Dataset/test.csv
  Mobile Price Classification/Dataset/train.csv
  Mobile Price Classification/Images/180277669-a01c509c-138b-4a5b-8c7f-9a0f607683ea.png
  Mobile Price Classification/Images/180277676-b313af06-744a-4094-8aaa-d36d32b7b9ce.png
  Mobile Price Classification/Images/180277685-f00f08b8-9577-40d2-a07f-001fa22b0b3d.png
  Mobile Price Classification/Images/180277696-85031ab7-4699-45e2-b225-83ee3d5313fd.png
  Mobile Price Classification/Images/180277706-48db8598-3fa1-4ce5-8a5f-637e0751c091.png
  Mobile Price Classification/Images/180277835-59f85a42-d00c-441e-9b4b-3700ce49d028.png
  Mobile Price Classification/Images/180277895-f4fdbacd-b010-4f05-ab7f-570bc74e288c.png
  Mobile Price Classification/Images/180277973-b1abdea1-223e-49c9-b15e-ac5dde2663e0.png
  Mobile Price Classification/Images/180277979-cfca251e-38b5-4170-b827-d16b221b3c93.png
  Mobile Price Classification/Images/180278006-d7606dbc-8afb-4ad3-aa11-0f73266ef893.png
  Mobile Price Classification/Images/180278029-86521940-c474-4244-b727-91343c1b0826.png
  Mobile Price Classification/Images/180278075-d7c6c048-bb55-4042-b319-67a13ac90eb5.png
  Mobile Price Classification/Images/180278152-81d7f8fb-9bff-47bc-8449-2050dc912d80.png
  Mobile Price Classification/Images/180278174-12cfbe13-03a7-4205-95b2-3a43aeea4d22.png
  Mobile Price Classification/Images/180278190-698e5373-27fa-4980-a5c6-e4561eaa364d.png
  Mobile Price Classification/Images/180278199-47192fcf-ed5b-42b7-808a-a7c9f09d05d2.png
  Mobile Price Classification/Images/180278210-a0810782-b58d-4758-addf-bf5cc4c5cb17.png
  Mobile Price Classification/Images/180278222-9ec16e91-168b-4579-b547-434b88c60e85.png
  Mobile Price Classification/Images/180278232-774ff7c6-9623-4b55-a63a-8e94d9f90ab3.png
  Mobile Price Classification/Images/180278243-41d48a67-3809-47a8-bd72-4d926a27026c.png
  Mobile Price Classification/Images/180278259-585fadc6-ce96-4fc3-bd58-e48efc79a299.png
  Mobile Price Classification/Images/180278285-26257b1b-0ca9-45b4-a9dc-ec896145eb11.png
  Mobile Price Classification/Images/180278369-10e062ca-b682-4eef-83dc-83f3995a6bb2.png
  Mobile Price Classification/Images/180278426-b4344671-0faa-45c9-96a1-914ab81fb401.png
  Mobile Price Classification/Images/180278484-384ce7d9-a585-408a-9a9f-b10812839729.png
  Mobile Price Classification/Images/180278533-1c1ccaac-d9d2-4c29-b7d2-b61b81c06b4e.png
  Mobile Price Classification/Images/180278550-374e352b-8529-4c19-b43a-6fd8c841c2a0.png
  Mobile Price Classification/Images/180278609-e818d65d-9edd-47d0-b8a2-e1ceb6977091.png
  Mobile Price Classification/Images/180278621-4c2f3031-fc3f-4891-b4bc-fb679d830a3e.png
  Mobile Price Classification/Images/180278707-c9a3116d-dfd3-4588-bdf8-935aee17c8f0.png
  Mobile Price Classification/Images/180280307-97453e2e-ab29-4c91-9a97-9dc32c863316.png
  Mobile Price Classification/Model/Mobile Price Classification.ipynb
  Mobile Price Classification/Model/README.md
  Mobile Price Classification/Model/test.csv
  Mobile Price Classification/Model/train.csv
  Mobile Price Classification/requiremnets.txt
Labels: Approved :white_check_mark:, HSOC22-Level-2

#304 Reddit Vaccine Myths Analysis File
  Reddit Vaccine Myths Analysis/Dataset/reddit_vm.csv
  Reddit Vaccine Myths Analysis/Images/180482033-d8e6e7f6-b21b-47ee-8f64-c38b3b52aac9.png
  Reddit Vaccine Myths Analysis/Images/180482047-7909c229-2355-4ecb-9a68-1397733716d8.png
  Reddit Vaccine Myths Analysis/Images/180482075-eb54172e-3ae2-410a-9f91-6cea93f140c4.png
  Reddit Vaccine Myths Analysis/Images/180482088-51de6872-6e31-4ef1-914a-d63fe8867827.png
  Reddit Vaccine Myths Analysis/Images/180482092-41b34925-d087-46e8-8419-b8d651e33908.png
  Reddit Vaccine Myths Analysis/Model/README.md
  Reddit Vaccine Myths Analysis/Model/Reddit Vaccine Myths Analysis.ipynb
  Reddit Vaccine Myths Analysis/Model/reddit_vm.csv
  Reddit Vaccine Myths Analysis/requiremnets.txt
Labels: Approved :white_check_mark:, HSOC22-Level-2

#309 Doge inr analysis
  Doge INR Analysis/Dataset/DOGE-INR.csv
  Doge INR Analysis/Dataset/dataset.md
  Doge INR Analysis/Images/close price scatter.png
  Doge INR Analysis/Images/high price.png
  Doge INR Analysis/Images/high price_scatter.png
  Doge INR Analysis/Images/linear.png
  Doge INR Analysis/Images/low price.png
  Doge INR Analysis/Images/open price.png
  Doge INR Analysis/Images/open price_scatter.png
  Doge INR Analysis/Images/ploy.png
  Doge INR Analysis/Images/residual.png
  Doge INR Analysis/Images/volume.png
  Doge INR Analysis/Model/.ipynb_checkpoints/dogecoin-inr-price-analysis-checkpoint.ipynb
  Doge INR Analysis/Model/README.md
  Doge INR Analysis/Model/dogecoin-inr-price-analysis.ipynb
  Doge INR Analysis/requirements.txt
Labels: Approved :white_check_mark:, HSOC22-Level-2

#310 OkCupid Profiles Analysis File
  OkCupid Profiles Analysis/Images/180602690-386b0428-37cd-497b-81f4-a367e4cdb4e5.png
  OkCupid Profiles Analysis/Images/180602692-314aa88d-9278-4319-a41f-3e1e1ac39836.png
  OkCupid Profiles Analysis/Images/180602696-899745fb-2491-4c11-915e-a8e420dd654f.png
  OkCupid Profiles Analysis/Images/180602700-ade00348-bb6c-451f-a3eb-7147e426490d.png
  OkCupid Profiles Analysis/Images/180602702-57984f25-1d14-4e56-b645-45312b7b61f7.png
  OkCupid Profiles Analysis/Images/180602706-7229335b-5ee2-4141-aa3b-a5e51c369a63.png
  OkCupid Profiles Analysis/Images/180602709-02224ebe-900e-43f4-b841-ab7852f77449.png
  OkCupid Profiles Analysis/Model/OkCupid Profiles Analysis .ipynb
  OkCupid Profiles Analysis/Model/README.md
  OkCupid Profiles Analysis/requiremnets.txt
Labels: Approved :white_check_mark:, HSOC22-Level-2

#327 Car Purchasing Prediction
  Car Purchasing Prediction/DataSet/README.md
  Car Purchasing Prediction/DataSet/car_data.csv
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 10.55.49 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 10.55.57 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 10.56.05 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 10.56.11 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 10.56.17 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 10.56.22 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 10.56.30 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 10.56.36 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 11.12.01 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 11.12.09 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 11.12.17 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 11.12.25 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 11.13.20 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 11.13.27 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 11.13.33 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 9.23.46 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 9.23.54 PM.png
  Car Purchasing Prediction/Images/Screenshot 2022-07-25 at 9.24.01 PM.png
  Car Purchasing Prediction/Model/Car Purchasing Prediction..ipynb
  Car Purchasing Prediction/Model/car_data.csv
  Car Purchasing Prediction/README.md
Labels: Approved :white_check_mark:, HSOC22-Level-3

#329 Premier League Match Analysis
  Premier League Match Analysis/Dataset/epl2020.csv
  Premier League Match Analysis/Images/current_points_table.png
  Premier League Match Analysis/Model/README.md
  Premier League Match Analysis/Model/epl_match_analysis.ipynb
  Premier League Match Analysis/requirements.txt
Labels: Approved :white_check_mark:, HSOC22-Level-2

#338 MAKAAN Analysis File
  MAKAAN Analysis/Images/181585856-1a37f542-ccbc-438d-acc5-cd72256d70af.png
  MAKAAN Analysis/Images/181585892-e8d8519f-a1ad-4159-a342-6ea97d334b66.png
  MAKAAN Analysis/Images/181585952-5ba42919-d0fa-4e2d-b2c2-67697cd701ab.png
  MAKAAN Analysis/Images/181585995-151cd626-755b-4086-a00f-696c81431ab3.png
  MAKAAN Analysis/Images/181586016-caf7fcb5-7268-41aa-b7d0-4eaecaece756.png
  MAKAAN Analysis/Images/181586085-14965e11-6db9-42c2-8556-ede370c57ecc.png
  MAKAAN Analysis/Images/181586110-ff400130-6839-4a4b-a246-fcbbf2518cfe.png
  MAKAAN Analysis/Images/181586138-4d2b16c7-3dad-48bd-b025-2fbfa3919348.png
  MAKAAN Analysis/Images/181586171-5b022df1-6d64-4547-abcc-c58f740b4fa3.png
  MAKAAN Analysis/Images/181586230-0d1050fa-1f22-4eab-9357-f854a99b53ab.png
  MAKAAN Analysis/Images/181586256-54ea720f-d31a-4e1e-8da3-ddaeab55dc3d.png
  MAKAAN Analysis/Images/181586275-11931a67-70e5-497c-b2a3-5c0b80ef4fb0.png
  MAKAAN Analysis/Images/181586298-50e56033-970e-4c3d-9aeb-40eca498db9b.png
  MAKAAN Analysis/Images/181586321-6444ed7c-43f0-4688-9dc7-c577eae218ac.png
  MAKAAN Analysis/Images/181586339-1173472f-f505-4dcd-aa28-a404ceb20031.png
  MAKAAN Analysis/Images/181586423-37cc2ad1-d9cc-42fd-bea3-3a185bbc486f.png
  MAKAAN Analysis/Model/MAKAAN Analysis.ipynb
  MAKAAN Analysis/Model/README.md
  MAKAAN Analysis/requiremnets.txt
Labels: Approved :white_check_mark:, HSOC22-Level-2

#340 Nifty 50 Analysis
  Nifty 50 Analysis/DataSet/CSV FILES/NIFTY 50.csv
  Nifty 50 Analysis/DataSet/CSV FILES/NIFTY AUTO.csv
  Nifty 50 Analysis/DataSet/CSV FILES/NIFTY BANK.csv
  Nifty 50 Analysis/DataSet/CSV FILES/NIFTY FMCG.csv
  Nifty 50 Analysis/DataSet/CSV FILES/NIFTY IT.csv
  Nifty 50 Analysis/DataSet/CSV FILES/NIFTY METAL.csv
  Nifty 50 Analysis/DataSet/CSV FILES/NIFTY MIDCAP 150.csv
  Nifty 50 Analysis/DataSet/CSV FILES/NIFTY NEXT 50.csv
  Nifty 50 Analysis/DataSet/CSV FILES/NIFTY OILGAS.csv
  Nifty 50 Analysis/DataSet/CSV FILES/NIFTY PHARMA.csv
  Nifty 50 Analysis/DataSet/CSV FILES/NIFTY SMALLCAP 250.csv
  Nifty 50 Analysis/DataSet/CSV FILES/Nifty Private_Bank.csv
  Nifty 50 Analysis/DataSet/CSV FILES/README.md
  Nifty 50 Analysis/Images/Screenshot 2022-07-30 at 2.19.26 PM.png
  Nifty 50 Analysis/Images/Screenshot 2022-07-30 at 2.19.32 PM.png
  Nifty 50 Analysis/Images/Screenshot 2022-07-30 at 2.19.38 PM.png
  Nifty 50 Analysis/Images/Screenshot 2022-07-30 at 2.19.48 PM.png
  Nifty 50 Analysis/Images/Screenshot 2022-07-30 at 2.19.59 PM.png
  Nifty 50 Analysis/Images/Screenshot 2022-07-30 at 2.20.12 PM.png
  Nifty 50 Analysis/Model/Nifty Analysis.ipynb
  Nifty 50 Analysis/README.md
Labels: Requested Changes :gear:
