Repository abhisheks008/ML-Crate, pull requests merged in 2024-02, with the labels that each got.

#564 TOXIC COMMENT ANALYSIS
  Toxic Comment Analysis/Dataset/EI-reg-En-anger-train.txt
  Toxic Comment Analysis/Images/1.png
  Toxic Comment Analysis/Images/2.png
  Toxic Comment Analysis/Images/3.png
  Toxic Comment Analysis/Models/Model.ipynb
  Toxic Comment Analysis/README.md
  Toxic Comment Analysis/requirements.txt
Labels: Approved :white_check_mark:, Medium, JWOC

#567 World Population Growth Analysis
  World Population Growth Analysis/Dataset/world-country-populations.csv
  World Population Growth Analysis/Images/'Top 20 Cities by Population Growth Rate'.png
  World Population Growth Analysis/Images/Bottom 20 Cities by Population Growth Rate.png
  World Population Growth Analysis/Images/Population Comparison between 2022 and 2023 by Country.png
  World Population Growth Analysis/Images/Population Comparison between 2022 and 2023 for Cities in the USA.png
  World Population Growth Analysis/Images/Population Growth Rate by Country.png
  World Population Growth Analysis/Images/Population Growth Rate for Cities in the USA.png
  World Population Growth Analysis/Images/Population Growth Rate vs Population in 2022.png
  World Population Growth Analysis/Images/Top 10 Cities with Highest Population in 2022.png
  World Population Growth Analysis/Images/Top 10 Cities with Highest Population in 2023.png
  World Population Growth Analysis/Images/Top 10 Countries with Highest Population in 2022.png
  World Population Growth Analysis/Images/Top 10 Countries with Highest Population in 2023.png
  World Population Growth Analysis/Model/README.md
  World Population Growth Analysis/Model/World_Population_Growth_Analysis.ipynb
  World Population Growth Analysis/requirements.txt
Labels: Approved :white_check_mark:, Medium, JWOC

#568 IELTS Success Analysis and Prediction Model
  IELTS Success Analysis and Prediction/Dataset/README.md
  IELTS Success Analysis and Prediction/Images/Application Status_feature.png
  IELTS Success Analysis and Prediction/Images/Location_feature.png
  IELTS Success Analysis and Prediction/Images/Study Duration (months)_feature.png
  IELTS Success Analysis and Prediction/Images/correlation_heatmap.png
  IELTS Success Analysis and Prediction/Images/target_correlation.png
  IELTS Success Analysis and Prediction/Model/ielts-success-analysis-and-prediction.ipynb
  IELTS Success Analysis and Prediction/README.md
  IELTS Success Analysis and Prediction/requirements.txt
Labels: Approved :white_check_mark:, Hard, IWOC2024

#578 Cardiovascular Disease Analysis and Prediction Model
  Cardiovascular Disease Analysis and Prediction/Dataset/README.md
  Cardiovascular Disease Analysis and Prediction/Images/age_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/correlation_heatmap.png
  Cardiovascular Disease Analysis and Prediction/Images/restingrelectro_feature.png
  Cardiovascular Disease Analysis and Prediction/Images/target_correlation.png
  Cardiovascular Disease Analysis and Prediction/Model/cardiovascular-disease-analysis-and-prediction.ipynb
  Cardiovascular Disease Analysis and Prediction/README.md
  Cardiovascular Disease Analysis and Prediction/requirements.txt
Labels: Approved :white_check_mark:, Hard, IWOC2024

#579 Top foreign language analysis #519
  Top Foreign Languages Analysis/Dataset/README.md
  Top Foreign Languages Analysis/Images/correlation between amount of lessons and price per lesson.png
  Top Foreign Languages Analysis/Images/count of tutors.png
  Top Foreign Languages Analysis/Images/distribution plot.png
  Top Foreign Languages Analysis/Model/Top_Foreign_Language_Analysis.ipynb
  Top Foreign Languages Analysis/README.md
  Top Foreign Languages Analysis/requirements.txt
Labels: Approved :white_check_mark:, Medium, JWOC

#583 Weather analysis #571
  Weather Analysis/Dataset/README.md
  Weather Analysis/Images/avg barometer vs rainfall per mnth.png
  Weather Analysis/Images/avg dewpoint vs rainfall per mnth.png
  Weather Analysis/Images/avg gutspeed vs rainfall per mnth.png
  Weather Analysis/Images/avg humidity vs rainfall per mnth.png
  Weather Analysis/Images/avg temp vs rainfall per mnth.png
  Weather Analysis/Images/avg windspeed vs rainfall per mnth.png
  Weather Analysis/Images/distribution plot 1.png
  Weather Analysis/Images/distribution plot 2.png
  Weather Analysis/Images/distribution plot 3.png
  Weather Analysis/Images/max humidity vs rainfall per mnth.png
  Weather Analysis/Images/max temp vs rainfall per mnth.png
  Weather Analysis/Images/month vs rainfall per month.png
  Weather Analysis/Model/Weather_Analysis.ipynb
  Weather Analysis/README.md
  Weather Analysis/requirements.txt
Labels: Approved :white_check_mark:, Hard, JWOC

#586 Emotion recognition in text
  Emotion Recognition In Text/Dataset/README.md
  Emotion Recognition In Text/Images/content length.png
  Emotion Recognition In Text/Images/sentiment distribution.png
  Emotion Recognition In Text/Images/sentiment piegraph.png
  Emotion Recognition In Text/Images/worldcloud1.png
  Emotion Recognition In Text/Model/Emotion-Recognition-in-text.ipynb
  Emotion Recognition In Text/README.md
  Emotion Recognition In Text/requirements.txt
Labels: Approved :white_check_mark:, Medium, JWOC

#587 Sentiment analysis for restaurant reviews (nlp) #584
  Sentiment Analysis for Restaurant Reviews (NLP) /Dataset/README.md
  Sentiment Analysis for Restaurant Reviews (NLP) /Images/Number_of_characters_in_each_review.png
  Sentiment Analysis for Restaurant Reviews (NLP) /Images/barchart.png
  Sentiment Analysis for Restaurant Reviews (NLP) /Images/negative_wordcloud.png
  Sentiment Analysis for Restaurant Reviews (NLP) /Images/piechart.png
  Sentiment Analysis for Restaurant Reviews (NLP) /Images/wordcloud_positive.png
  Sentiment Analysis for Restaurant Reviews (NLP) /Model/Sentiment_Analysis_for_Restaurant_Reviews_(NLP).ipynb
  Sentiment Analysis for Restaurant Reviews (NLP) /README.md
  Sentiment Analysis for Restaurant Reviews (NLP) /requirements.txt
Labels: Approved :white_check_mark:, Medium, JWOC

#588 Google Playstore Analysis and Rating Prediction
  Google Playstore Analysis And Rating Predictor/Dataset/googleplaystore.csv
  Google Playstore Analysis And Rating Predictor/Images/App distribution by category.png
  Google Playstore Analysis And Rating Predictor/Images/App distribution sunburst chart by category.png
  Google Playstore Analysis And Rating Predictor/Images/App size distribution by category.png
  Google Playstore Analysis And Rating Predictor/Images/Average Price By category.png
  Google Playstore Analysis And Rating Predictor/Images/Category by Content Rating.png
  Google Playstore Analysis And Rating Predictor/Images/Distribution of App Sizes.png
  Google Playstore Analysis And Rating Predictor/Images/Number of applications by content rating.png
  Google Playstore Analysis And Rating Predictor/Images/Number of apps by type.png
  Google Playstore Analysis And Rating Predictor/Images/Scatter plot of reviews vs installs.png
  Google Playstore Analysis And Rating Predictor/Images/Total installs by category.png
  Google Playstore Analysis And Rating Predictor/Images/Word Cloud for Genre Column.png
  Google Playstore Analysis And Rating Predictor/Images/wordcloud for category column.png
  Google Playstore Analysis And Rating Predictor/Model/Google_Playstore_Analysis_and_Rating_Prediction.ipynb
  Google Playstore Analysis And Rating Predictor/Model/README.md
  Google Playstore Analysis And Rating Predictor/Requirements.txt
Labels: Approved :white_check_mark:, Medium, JWOC

#590 LinkedIn Poll Data Analysis
  LinkedIn Poll Data Analysis/Dataset/LIQuizPollData%20-%20Sheet1%20(2).csv
  LinkedIn Poll Data Analysis/Images/all_features.png
  LinkedIn Poll Data Analysis/Images/decision_tree.png
  LinkedIn Poll Data Analysis/Images/heat_map.png
  LinkedIn Poll Data Analysis/Images/linear_reg.png
  LinkedIn Poll Data Analysis/Images/popularity_of_quiz.png
  LinkedIn Poll Data Analysis/Images/random_forest.png
  LinkedIn Poll Data Analysis/Images/smv.png
  LinkedIn Poll Data Analysis/Images/tot_responses.png
  LinkedIn Poll Data Analysis/Model/Linkedln_poll_analysis.ipynb
  LinkedIn Poll Data Analysis/Model/README.md
  LinkedIn Poll Data Analysis/requirements.txt
Labels: Approved :white_check_mark:, Medium, JWOC

#591 Most Subscribed YouTube Channels Analysis #575
  Most Subscribed YouTube Channels Analysis/Dataset/README.md
  Most Subscribed YouTube Channels Analysis/Images/IMG1.png
  Most Subscribed YouTube Channels Analysis/Images/img2.png
  Most Subscribed YouTube Channels Analysis/Images/img3.png
  Most Subscribed YouTube Channels Analysis/Images/img4.png
  Most Subscribed YouTube Channels Analysis/Images/img5.png
  Most Subscribed YouTube Channels Analysis/Images/img6.png
  Most Subscribed YouTube Channels Analysis/Images/img7.png
  Most Subscribed YouTube Channels Analysis/Images/img8.png
  Most Subscribed YouTube Channels Analysis/Images/img9.png
  Most Subscribed YouTube Channels Analysis/Model/Most_Subscribed_YouTube_Channels_Analysis.ipynb
  Most Subscribed YouTube Channels Analysis/README.md
  Most Subscribed YouTube Channels Analysis/requirements.txt
Labels: Approved :white_check_mark:, Medium, JWOC
