Repository abhisheks008/ML-Crate, pull requests merged in 2024-06, with the labels that each got.

#604 [README Enhacement]: ASELSAN Stock Prices
  ASELSAN Stock Prices/Model/README.md
Labels: Approved :white_check_mark:, Beginner, SSOC

#628 [README Enhancement]: Advertisement Click Prediction
  Advertisement Click Prediction/Model/README.md
Labels: Approved :white_check_mark:, Beginner, SSOC

#627 Viral Shorts Video Analysis
  Viral Shorts Video Analysis/Dataset/README.md
  Viral Shorts Video Analysis/Dataset/most_viewed_youtube_shorts.csv
  Viral Shorts Video Analysis/Images/1)most_common_words.png
  Viral Shorts Video Analysis/Images/2)word_cloud.png
  Viral Shorts Video Analysis/Images/3)pair_plot.png
  Viral Shorts Video Analysis/Images/4)heat_map.png
  Viral Shorts Video Analysis/Images/5)fequency_of_likes.png
  Viral Shorts Video Analysis/Images/6)distribution of video duration.png
  Viral Shorts Video Analysis/Images/7)time_series_of_views.png
  Viral Shorts Video Analysis/Models/README.md
  Viral Shorts Video Analysis/Models/model.ipynb
  Viral Shorts Video Analysis/requirements.txt
Labels: Approved :white_check_mark:, Advanced, SSOC

#638 The Effect of Economic News on Gold Prices Analysis
  The Effect of Economic News on Gold Prices Analysis/Dataset/README.md
  The Effect of Economic News on Gold Prices Analysis/Dataset/economic_calendar_19_24.csv
  The Effect of Economic News on Gold Prices Analysis/Dataset/gold_price_19_24.csv
  The Effect of Economic News on Gold Prices Analysis/Dataset/sentiment_labeled_data.csv
  The Effect of Economic News on Gold Prices Analysis/Images/Accuracies of Models.png
  The Effect of Economic News on Gold Prices Analysis/Images/Avg Price by country.png
  The Effect of Economic News on Gold Prices Analysis/Images/Dist of events per date.png
  The Effect of Economic News on Gold Prices Analysis/Images/Dist of price by country.png
  The Effect of Economic News on Gold Prices Analysis/Images/HeatMap Of Correlation.png
  The Effect of Economic News on Gold Prices Analysis/Images/Trend of Price&Vol_K.png
  The Effect of Economic News on Gold Prices Analysis/Images/Weekly-Gold.png
  The Effect of Economic News on Gold Prices Analysis/Model/README.md
  The Effect of Economic News on Gold Prices Analysis/Model/project_folder.ipynb
  The Effect of Economic News on Gold Prices Analysis/requirements.txt
Labels: Approved :white_check_mark:, Intermediate, SSOC

#642 Medical Recommendation System
  Medical Recommendation System/Dataset/README.md
  Medical Recommendation System/Dataset/Symptom-severity.csv
  Medical Recommendation System/Dataset/description.csv
  Medical Recommendation System/Dataset/diets.csv
  Medical Recommendation System/Dataset/medical_dataset.csv
  Medical Recommendation System/Dataset/medications.csv
  Medical Recommendation System/Dataset/precautions_df.csv
  Medical Recommendation System/Dataset/symtoms_df.csv
  Medical Recommendation System/Dataset/workout_df.csv
  Medical Recommendation System/Images/ANN_model_summary.png
  Medical Recommendation System/Images/Count_of_each_disease.png
  Medical Recommendation System/Images/README.md
  Medical Recommendation System/Images/ROC_comparison_of_models.png
  Medical Recommendation System/Images/ROC_curve_artificial_neural_networks.png
  Medical Recommendation System/Images/ROC_curve_decision_tree.png
  Medical Recommendation System/Images/ROC_curve_gradient_boosting.png
  Medical Recommendation System/Images/ROC_curve_k_nearest_neighbors.png
  Medical Recommendation System/Images/ROC_curve_logistic_regression.png
  Medical Recommendation System/Images/ROC_curve_naive_bayes.png
  Medical Recommendation System/Images/ROC_curve_random_forest.png
  Medical Recommendation System/Images/ROC_curve_support_vector_classifier.png
  Medical Recommendation System/Images/SVC_model_accuracy_and_precision.png
  Medical Recommendation System/Images/accuracy_comparison_of_models.png
  Medical Recommendation System/Images/confusion_matrix_of_best_model.png
  Medical Recommendation System/Images/heatmap.png
  Medical Recommendation System/Model/README.md
  Medical Recommendation System/Model/medical_recommendation_system.ipynb
  Medical Recommendation System/README.md
  Medical Recommendation System/requirements.txt
Labels: Approved :white_check_mark:, Advanced, SSOC

#646 New BRICS Member Sentiment Analysis #518
  New BRICS Member Sentiment Analysis/Dataset/BRICS.csv
  New BRICS Member Sentiment Analysis/Dataset/README.md
  New BRICS Member Sentiment Analysis/Images/LightGBM_output.png
  New BRICS Member Sentiment Analysis/Images/README.md
  New BRICS Member Sentiment Analysis/Images/advance_stacking_output.png
  New BRICS Member Sentiment Analysis/Images/cmp_all_model.png
  New BRICS Member Sentiment Analysis/Images/distribution.png
  New BRICS Member Sentiment Analysis/Images/likecount.png
  New BRICS Member Sentiment Analysis/Images/lstm_output.png
  New BRICS Member Sentiment Analysis/Images/mlp_output.png
  New BRICS Member Sentiment Analysis/Images/simple_neural_network_output.png
  New BRICS Member Sentiment Analysis/Images/stacking_classifier_confusion.png
  New BRICS Member Sentiment Analysis/Images/webapp_run.mp4
  New BRICS Member Sentiment Analysis/Images/wordcloud.png
  New BRICS Member Sentiment Analysis/Model/BRICS_Sentiment_analysis.ipynb
  New BRICS Member Sentiment Analysis/Model/README.md
  New BRICS Member Sentiment Analysis/Model/lgb_model.pkl
  New BRICS Member Sentiment Analysis/README.md
  New BRICS Member Sentiment Analysis/Webapp/README.md
  New BRICS Member Sentiment Analysis/Webapp/app.py
  New BRICS Member Sentiment Analysis/requirement.txt
Labels: Approved :white_check_mark:, Advanced, SSOC

#648 Automobiles Sales Data Analysis #576
  Automobile Sales Data Analysis/Dataset/Auto_Sales_data.csv
  Automobile Sales Data Analysis/Dataset/README.md
  Automobile Sales Data Analysis/Images/customer.png
  Automobile Sales Data Analysis/Images/heatmap.png
  Automobile Sales Data Analysis/Images/model.png
  Automobile Sales Data Analysis/Images/order_status.png
  Automobile Sales Data Analysis/Images/product_line.png
  Automobile Sales Data Analysis/Images/sales_by_country.png
  Automobile Sales Data Analysis/Images/sales_by_day.png
  Automobile Sales Data Analysis/Images/size.png
  Automobile Sales Data Analysis/Model/README.md
  Automobile Sales Data Analysis/Model/model.ipynb
  Automobile Sales Data Analysis/requirements.txt
Labels: Approved :white_check_mark:, Advanced, SSOC

#641 Automobile Sales Data Analysis and Prediction
  Automobile Sales Data Analysis and Prediction/Dataset/Auto Sales data.csv
  Automobile Sales Data Analysis and Prediction/Dataset/README.md
  Automobile Sales Data Analysis and Prediction/Images/Dealsize_bar.png
  Automobile Sales Data Analysis and Prediction/Images/Dealsize_pie.png
  Automobile Sales Data Analysis and Prediction/Images/Productline_bar.png
  Automobile Sales Data Analysis and Prediction/Images/Productline_pie.png
  Automobile Sales Data Analysis and Prediction/Images/Status_bar.png
  Automobile Sales Data Analysis and Prediction/Images/Status_pie.png
  Automobile Sales Data Analysis and Prediction/Model/Automobile_Sales_Prediction.ipynb
  Automobile Sales Data Analysis and Prediction/Model/README.md
  Automobile Sales Data Analysis and Prediction/requirements.txt
Labels: Approved :white_check_mark:, Advanced, SSOC

#643 Facial Landmark Detection Using Python's MediaPipe Library
  Facial Landmark Detection/Model/code_v2.ipynb
  Facial Landmark Detection/Model/source_code.ipynb
  Facial Landmark Detection/README.md
  Facial Landmark Detection/images/pexels-david-garrison-1128051-2128807.jpg
  Facial Landmark Detection/images/pexels-italo-melo-881954-2379005.jpg
  Facial Landmark Detection/images/pexels-pixabay-415829.jpg
  Facial Landmark Detection/images/pexels-simon-robben-55958-614810.jpg
  Facial Landmark Detection/requirements.txt
  Facial Landmark Detection/webapp/README.md
  Facial Landmark Detection/webapp/app.py
Labels: Approved :white_check_mark:, Intermediate, SSOC

#640 [Project Enhancement]: Brain Stroke Prediction using Neural Networks
  Brain Stroke Prediction/New/Dataset/README.md
  Brain Stroke Prediction/New/Dataset/healthcare-dataset-stroke-data.csv
  Brain Stroke Prediction/New/Model/Brain_Stroke_NN.ipynb
  Brain Stroke Prediction/New/Model/README.md
  Brain Stroke Prediction/New/Pictures/Screenshot 2024-06-08 001109.png
  Brain Stroke Prediction/New/Pictures/Screenshot 2024-06-08 001118.png
  Brain Stroke Prediction/New/Pictures/Screenshot 2024-06-08 001128.png
  Brain Stroke Prediction/New/Pictures/Screenshot 2024-06-08 001134.png
  Brain Stroke Prediction/New/requirements.txt
  Brain Stroke Prediction/Old/Dataset/archive-2/README.md
  Brain Stroke Prediction/Old/Dataset/archive-2/full_data.csv
  Brain Stroke Prediction/Old/Dataset/archive-2/full_filled_stroke_data (1).csv
  Brain Stroke Prediction/Old/Model/Brain Stroke Prediction.ipynb
  Brain Stroke Prediction/Old/Pictures/Screenshot 2022-08-02 at 9.44.56 PM.png
  Brain Stroke Prediction/Old/Pictures/Screenshot 2022-08-02 at 9.45.06 PM.png
  Brain Stroke Prediction/Old/Pictures/Screenshot 2022-08-02 at 9.45.15 PM.png
  Brain Stroke Prediction/Old/Pictures/Screenshot 2022-08-02 at 9.45.22 PM.png
  Brain Stroke Prediction/Old/Pictures/Screenshot 2022-08-02 at 9.45.31 PM.png
  Brain Stroke Prediction/Old/Pictures/Screenshot 2022-08-02 at 9.45.39 PM.png
  Brain Stroke Prediction/Old/Pictures/Screenshot 2022-08-02 at 9.45.47 PM.png
  Brain Stroke Prediction/Old/Pictures/Screenshot 2022-08-02 at 9.45.54 PM.png
  Brain Stroke Prediction/Old/Pictures/Screenshot 2022-08-02 at 9.46.05 PM.png
  Brain Stroke Prediction/Old/Pictures/Screenshot 2022-08-02 at 9.46.12 PM.png
  Brain Stroke Prediction/Old/README.md
Labels: Approved :white_check_mark:, Intermediate, SSOC

#635 Pcos Detection
  Pcos Detection/Dataset/PCOS_infertility.csv
  Pcos Detection/Images/Screenshot 2024-06-07 113900.png
  Pcos Detection/Images/Screenshot 2024-06-07 113949.png
  Pcos Detection/Images/Screenshot 2024-06-07 114008.png
  Pcos Detection/Images/Screenshot 2024-06-07 114026.png
  Pcos Detection/Images/Screenshot 2024-06-07 114043.png
  Pcos Detection/Images/Screenshot 2024-06-07 114101.png
  Pcos Detection/Images/Screenshot 2024-06-07 114118.png
  Pcos Detection/Model/Pcos Detection.ipynb
  Pcos Detection/Model/README.md
  Pcos Detection/requirements.txt
Labels: Approved :white_check_mark:, Intermediate, SSOC

#654 Cement Strength Prediction
  Cement Strength Prediction/Dataset/Cement Strength Data.csv
  Cement Strength Prediction/README.md
  Cement Strength Prediction/images/__results___10_0.png
  Cement Strength Prediction/images/__results___11_0.png
  Cement Strength Prediction/images/__results___12_0.png
  Cement Strength Prediction/images/__results___13_0.png
  Cement Strength Prediction/images/__results___18_0.png
  Cement Strength Prediction/images/__results___25_0.png
  Cement Strength Prediction/images/__results___26_0.png
  Cement Strength Prediction/images/__results___32_0.png
  Cement Strength Prediction/images/__results___33_0.png
  Cement Strength Prediction/images/__results___8_0.png
  Cement Strength Prediction/images/__results___9_0.png
  Cement Strength Prediction/model/README.md
  Cement Strength Prediction/model/cement-strength-prediction.ipynb
  Cement Strength Prediction/requirements.txt
Labels: Approved :white_check_mark:, Advanced, SSOC

#672 Sarcasm Detection Model using Machine Learning(NLP)
  Sarcasm detection using NLP/Dataset/dataset
  Sarcasm detection using NLP/Images/model1_acc.png
  Sarcasm detection using NLP/Images/model1_loss.png
  Sarcasm detection using NLP/Images/model2_acc.png
  Sarcasm detection using NLP/Images/model2_loss.png
  Sarcasm detection using NLP/Images/model3_acc.png
  Sarcasm detection using NLP/Images/model3_loss.png
  Sarcasm detection using NLP/Images/model4_acc.png
  Sarcasm detection using NLP/Images/model4_loss.png
  Sarcasm detection using NLP/Images/model5_acc.png
  Sarcasm detection using NLP/Images/model5_loss.png
  Sarcasm detection using NLP/Images/model6_acc.png
  Sarcasm detection using NLP/Images/model6_loss.png
  Sarcasm detection using NLP/Images/model7_acc.png
  Sarcasm detection using NLP/Images/model7_loss.png
  Sarcasm detection using NLP/Model/Sarcasm_detection_NLP.ipynb
  Sarcasm detection using NLP/README.md
  Sarcasm detection using NLP/requirements.txt
Labels: Approved :white_check_mark:, Ready To Merge :rocket:, MEDIUM, VSOC

#669 ACI IoT Network Traffic Dataset Analysis
  ACI IoT Network Traffic Dataset Analysis/Dataset/README.md
  ACI IoT Network Traffic Dataset Analysis/Images/Bar Graph.png
  ACI IoT Network Traffic Dataset Analysis/Images/Pie Chart.png
  ACI IoT Network Traffic Dataset Analysis/Model/ACI_IoT_Network_Traffic_Dataset_Analysis.ipynb
  ACI IoT Network Traffic Dataset Analysis/Model/README.md
  ACI IoT Network Traffic Dataset Analysis/requirements.txt
Labels: Approved :white_check_mark:, Intermediate, SSOC

#676 Ecommerce trends Analysis
  E-Commerce Trends Analysis/Dataset/ecommerce_product_dataset.csv
  E-Commerce Trends Analysis/Images/__results___13_0.png
  E-Commerce Trends Analysis/Images/__results___14_1.png
  E-Commerce Trends Analysis/Images/__results___15_0.png
  E-Commerce Trends Analysis/Images/__results___17_0.png
  E-Commerce Trends Analysis/Images/__results___18_2.png
  E-Commerce Trends Analysis/Images/__results___20_1.png
  E-Commerce Trends Analysis/Images/__results___21_1.png
  E-Commerce Trends Analysis/Images/__results___22_0.png
  E-Commerce Trends Analysis/Images/__results___23_0.png
  E-Commerce Trends Analysis/Images/__results___24_0.png
  E-Commerce Trends Analysis/Images/__results___25_0.png
  E-Commerce Trends Analysis/Images/__results___26_0.png
  E-Commerce Trends Analysis/Images/__results___27_0.png
  E-Commerce Trends Analysis/Images/__results___29_1.png
  E-Commerce Trends Analysis/Images/__results___31_1.png
  E-Commerce Trends Analysis/Images/__results___42_0.png
  E-Commerce Trends Analysis/Images/__results___43_0.png
  E-Commerce Trends Analysis/Images/__results___7_1.png
  E-Commerce Trends Analysis/Images/__results___8_1.png
  E-Commerce Trends Analysis/Images/__results___9_1.png
  E-Commerce Trends Analysis/Models/README.md
  E-Commerce Trends Analysis/Models/ecommerce-trends-eda-models (2).ipynb
  E-Commerce Trends Analysis/README.md
  E-Commerce Trends Analysis/Results/model_results.csv
  E-Commerce Trends Analysis/requirements.txt
Labels: Approved :white_check_mark:, MEDIUM, VSOC

#675 Salary Prediction of Data Professions
  Salary Predictions of Data Professionals/Dataset/README.md
  Salary Predictions of Data Professionals/Dataset/Salary Prediction of Data Professions.csv
  Salary Predictions of Data Professionals/Images/Machine Learning Model Development and Evaluation/Screenshot from 2024-06-11 11-13-30.png
  Salary Predictions of Data Professionals/Images/Machine Learning Model Development and Evaluation/Screenshot from 2024-06-11 11-15-28.png
  Salary Predictions of Data Professionals/Images/Machine Learning Model Development and Evaluation/actual vs prediction.png
  Salary Predictions of Data Professionals/Images/Machine Learning Model Development and Evaluation/actualvsprediction.png
  Salary Predictions of Data Professionals/Images/Machine Learning Model Development and Evaluation/model evaluation.png
  Salary Predictions of Data Professionals/Images/Machine Learning Model Development and Evaluation/model prediction.png
  Salary Predictions of Data Professionals/Images/Machine Learning Model Development and Evaluation/model_evaluation_result.png
  Salary Predictions of Data Professionals/Images/Machine Learning Model Development and Evaluation/model_selection.png
  Salary Predictions of Data Professionals/Images/README.md
  Salary Predictions of Data Professionals/Images/data preprocessing/Screenshot from 2024-06-11 11-03-48.png
  Salary Predictions of Data Professionals/Images/data preprocessing/data handling/Handle Date Columns and Calculate Tenure:.png
  Salary Predictions of Data Professionals/Images/data preprocessing/data handling/handle missing data.png
  Salary Predictions of Data Professionals/Images/data preprocessing/encoding.png
  Salary Predictions of Data Professionals/Images/data preprocessing/train and feature.png
  Salary Predictions of Data Professionals/Images/eda/check_for_null.png
  Salary Predictions of Data Professionals/Images/eda/correlation.png
  Salary Predictions of Data Professionals/Images/eda/describe.png
  Salary Predictions of Data Professionals/Images/eda/distribution of salary.png
  Salary Predictions of Data Professionals/Images/eda/head.png
  Salary Predictions of Data Professionals/Images/eda/info.png
  Salary Predictions of Data Professionals/Images/eda/salary vs age.png
  Salary Predictions of Data Professionals/Images/eda/salaryvsdesignation.png
  Salary Predictions of Data Professionals/Images/feature engenirring/Screenshot from 2024-06-11 10-47-06.png
  Salary Predictions of Data Professionals/Images/feature engenirring/Screenshot from 2024-06-11 10-49-00.png
  Salary Predictions of Data Professionals/Images/feature engenirring/Screenshot from 2024-06-11 10-55-36.png
  Salary Predictions of Data Professionals/Images/feature engenirring/Screenshot from 2024-06-11 10-56-11.png
  Salary Predictions of Data Professionals/Images/ml pipeline/Screenshot from 2024-06-11 00-47-56.png
  Salary Predictions of Data Professionals/Images/ml pipeline/Screenshot from 2024-06-11 11-26-26.png
  Salary Predictions of Data Professionals/Images/ml pipeline/create and train of pipeline.png
  Salary Predictions of Data Professionals/Images/ml pipeline/preprocessing for cateogarical input.png
  Salary Predictions of Data Professionals/Images/ml pipeline/preprocessiong for numeric factor.png
  Salary Predictions of Data Professionals/Model/README.md
  Salary Predictions of Data Professionals/Model/Salary Prediction of Data Professions.csv
  Salary Predictions of Data Professionals/Model/Salary_Predection.ipynb
  Salary Predictions of Data Professionals/README.md
  Salary Predictions of Data Professionals/Web App/README.md
  Salary Predictions of Data Professionals/Web App/app.py
  Salary Predictions of Data Professionals/Web App/best_salary_model.sav
  Salary Predictions of Data Professionals/Web App/demo.mp4
  Salary Predictions of Data Professionals/Web App/salary_prediction_pipeline_lr.pkl
  Salary Predictions of Data Professionals/Web App/static/styles.css
  Salary Predictions of Data Professionals/Web App/templates/index.html
  Salary Predictions of Data Professionals/requirements
Labels: Approved :white_check_mark:, Advanced, SSOC

#683 Cheese classification
  Cheese Classification/Dataset/cheeses.csv
  Cheese Classification/Images/__results___10_1.png
  Cheese Classification/Images/__results___12_1.png
  Cheese Classification/Images/__results___13_0.png
  Cheese Classification/Images/__results___16_0.png
  Cheese Classification/Images/__results___18_0.png
  Cheese Classification/Images/__results___19_0.png
  Cheese Classification/Images/__results___20_0.png
  Cheese Classification/Images/__results___22_0.png
  Cheese Classification/Images/__results___24_1.png
  Cheese Classification/Images/__results___25_1.png
  Cheese Classification/Images/__results___69_1.png
  Cheese Classification/Images/__results___69_10.png
  Cheese Classification/Images/__results___69_11.png
  Cheese Classification/Images/__results___69_2.png
  Cheese Classification/Images/__results___69_3.png
  Cheese Classification/Images/__results___69_4.png
  Cheese Classification/Images/__results___69_5.png
  Cheese Classification/Images/__results___69_6.png
  Cheese Classification/Images/__results___69_7.png
  Cheese Classification/Images/__results___69_8.png
  Cheese Classification/Images/__results___69_9.png
  Cheese Classification/Model/README.md
  Cheese Classification/Model/cheese-classification-eda-and-models.ipynb
  Cheese Classification/README.md
  Cheese Classification/requirements.txt
  Cheese Classification/results/AdaBoost_classification_report.csv
  Cheese Classification/results/AdaBoost_confusion_matrix.csv
  Cheese Classification/results/AdaBoost_confusion_matrix.png
  Cheese Classification/results/CatBoost_classification_report.csv
  Cheese Classification/results/CatBoost_confusion_matrix.csv
  Cheese Classification/results/CatBoost_confusion_matrix.png
  Cheese Classification/results/Decision Tree_classification_report.csv
  Cheese Classification/results/Decision Tree_confusion_matrix.csv
  Cheese Classification/results/Decision Tree_confusion_matrix.png
  Cheese Classification/results/Extra Trees_classification_report.csv
  Cheese Classification/results/Extra Trees_confusion_matrix.csv
  Cheese Classification/results/Extra Trees_confusion_matrix.png
  Cheese Classification/results/Gradient Boosting_classification_report.csv
  Cheese Classification/results/Gradient Boosting_confusion_matrix.csv
  Cheese Classification/results/Gradient Boosting_confusion_matrix.png
  Cheese Classification/results/K-Nearest Neighbors_classification_report.csv
  Cheese Classification/results/K-Nearest Neighbors_confusion_matrix.csv
  Cheese Classification/results/K-Nearest Neighbors_confusion_matrix.png
  Cheese Classification/results/Logistic Regression_classification_report.csv
  Cheese Classification/results/Logistic Regression_confusion_matrix.csv
  Cheese Classification/results/Logistic Regression_confusion_matrix.png
  Cheese Classification/results/Naive Bayes_classification_report.csv
  Cheese Classification/results/Naive Bayes_confusion_matrix.csv
  Cheese Classification/results/Naive Bayes_confusion_matrix.png
  Cheese Classification/results/Random Forest_classification_report.csv
  Cheese Classification/results/Random Forest_confusion_matrix.csv
  Cheese Classification/results/Random Forest_confusion_matrix.png
  Cheese Classification/results/Support Vector Machine_classification_report.csv
  Cheese Classification/results/Support Vector Machine_confusion_matrix.csv
  Cheese Classification/results/Support Vector Machine_confusion_matrix.png
  Cheese Classification/results/XGBoost_classification_report.csv
  Cheese Classification/results/XGBoost_confusion_matrix.csv
  Cheese Classification/results/XGBoost_confusion_matrix.png
Labels: Approved :white_check_mark:, Advanced, SSOC

#682 added student stress level detection project
  Student Stress Levels Detection/Dataset/README.md
  Student Stress Levels Detection/Dataset/student_stress_data.csv
  Student Stress Levels Detection/Images/box_plots.png
  Student Stress Levels Detection/Images/correlation_heatmap.png
  Student Stress Levels Detection/Images/reg_plots.png
  Student Stress Levels Detection/Images/stress_level_kde.png
  Student Stress Levels Detection/Model/model.pkl
  Student Stress Levels Detection/Model/student_stress_level_detection.ipynb
  Student Stress Levels Detection/README.md
  Student Stress Levels Detection/requirements.txt
Labels: Approved :white_check_mark:, Intermediate, SSOC
