Repository abhisheks008/ML-Crate, pull requests merged in 2024-01, with the labels that each got.

#456 BellaBeat - Capstone Project by Google
  BellaBeat - Capstone Project by Google/Dataset/.gitignore
  BellaBeat - Capstone Project by Google/Dataset/README.md
  BellaBeat - Capstone Project by Google/Images/calories_burned_by_day_of_the_week.png
  BellaBeat - Capstone Project by Google/Images/correlation_matrix.png
  BellaBeat - Capstone Project by Google/Images/linear_reg_1_x_test_vs_y_pred.png
  BellaBeat - Capstone Project by Google/Images/linear_reg_2_x_test_vs_y_pred.png
  BellaBeat - Capstone Project by Google/Images/most_and_least_active_hours_of_the_day.png
  BellaBeat - Capstone Project by Google/Images/sedentary_mins_vs_total_active_mins.png
  BellaBeat - Capstone Project by Google/Images/total_active_mins_vs_total_steps.png
  BellaBeat - Capstone Project by Google/Images/total_steps_and_sedentary_mins_vs_calories.png
  BellaBeat - Capstone Project by Google/Images/total_steps_taken_by_day_of_the_week.png
  BellaBeat - Capstone Project by Google/Images/total_steps_vs_calories.png
  BellaBeat - Capstone Project by Google/Images/total_time_asleep_by_day_of_the_week.png
  BellaBeat - Capstone Project by Google/Model/.ipynb_checkpoints/EDA-checkpoint.ipynb
  BellaBeat - Capstone Project by Google/Model/README.md
  BellaBeat - Capstone Project by Google/Model/analysis.ipynb
  BellaBeat - Capstone Project by Google/requirements.txt
Labels: Approved :white_check_mark:, KWOC 2023

#479 Bearing Classification
  Bearing Classification/Dataset/Faulty-bearing.csv
  Bearing Classification/Dataset/Healthy-bearing.csv
  Bearing Classification/Images/EDA1.png
  Bearing Classification/Images/EDA2.png
  Bearing Classification/Images/EDA3.png
  Bearing Classification/Images/Input_Dataset.png
  Bearing Classification/Images/Metrics.png
  Bearing Classification/Model/bearing_classification.ipynb
  Bearing Classification/README.md
Labels: Approved :white_check_mark:, KWOC 2023

#485 Create requirements.txt
  Stock News Sentiment Analysis/Model/requirements.txt
Labels: Approved :white_check_mark:, KWOC 2023

#484 Singaporean Cryptocurrency Analysis Completed
  Singaporean Cryptocurrency Analysis/Dataset/README.md
  Singaporean Cryptocurrency Analysis/Images/ADA-SGD.png
  Singaporean Cryptocurrency Analysis/Images/BNB-SGD.png
  Singaporean Cryptocurrency Analysis/Images/DOGE-SGD.png
  Singaporean Cryptocurrency Analysis/Images/ETH-SGD.png
  Singaporean Cryptocurrency Analysis/Images/LTC-SGD.png
  Singaporean Cryptocurrency Analysis/Images/MATIC-SGD.png
  Singaporean Cryptocurrency Analysis/Models/LSTM_results.csv
  Singaporean Cryptocurrency Analysis/Models/results.csv
  Singaporean Cryptocurrency Analysis/Models/singaporean_cryptocurrency_analysis.ipynb
  Singaporean Cryptocurrency Analysis/README.md
  Singaporean Cryptocurrency Analysis/requirements.txt
Labels: Approved :white_check_mark:, KWOC 2023

#488 Stanford Car Image Classification
  Stanford Car Image Classification/Dataset/readme.md
  Stanford Car Image Classification/Images/Accuracy of data augmented resnet34.png
  Stanford Car Image Classification/Images/Accuracy of resnet34.png
  Stanford Car Image Classification/Images/cnn1 accuracy.png
  Stanford Car Image Classification/Images/cnn1 loss.png
  Stanford Car Image Classification/Images/cnn2 accuracy.png
  Stanford Car Image Classification/Images/cnn2 loss.png
  Stanford Car Image Classification/Images/losses of data augmented resnet34.png
  Stanford Car Image Classification/Images/losses of resnet34.png
  Stanford Car Image Classification/Model/readme.md
  Stanford Car Image Classification/Model/stanford-car-image-classification.ipynb
  Stanford Car Image Classification/requirements.txt
Labels: Approved :white_check_mark:, KWOC 2023

#486 Nuclear weapons analysis
  Nuclear Weapons Analysis/Dataset/README.md
  Nuclear Weapons Analysis/Dataset/nuclear_weapons_proliferation_owid.csv
  Nuclear Weapons Analysis/Dataset/nuclear_weapons_proliferation_total_owid.csv
  Nuclear Weapons Analysis/Dataset/nuclear_weapons_stockpiles.csv
  Nuclear Weapons Analysis/Dataset/nuclear_weapons_tests_states.csv
  Nuclear Weapons Analysis/Images/nw1.PNG
  Nuclear Weapons Analysis/Images/nw10.PNG
  Nuclear Weapons Analysis/Images/nw11.PNG
  Nuclear Weapons Analysis/Images/nw12.PNG
  Nuclear Weapons Analysis/Images/nw13.PNG
  Nuclear Weapons Analysis/Images/nw14.PNG
  Nuclear Weapons Analysis/Images/nw15.PNG
  Nuclear Weapons Analysis/Images/nw16.PNG
  Nuclear Weapons Analysis/Images/nw17.PNG
  Nuclear Weapons Analysis/Images/nw18.PNG
  Nuclear Weapons Analysis/Images/nw19.PNG
  Nuclear Weapons Analysis/Images/nw2.PNG
  Nuclear Weapons Analysis/Images/nw20.PNG
  Nuclear Weapons Analysis/Images/nw21.PNG
  Nuclear Weapons Analysis/Images/nw3.PNG
  Nuclear Weapons Analysis/Images/nw4.PNG
  Nuclear Weapons Analysis/Images/nw5.PNG
  Nuclear Weapons Analysis/Images/nw6.PNG
  Nuclear Weapons Analysis/Images/nw7.PNG
  Nuclear Weapons Analysis/Images/nw8.PNG
  Nuclear Weapons Analysis/Images/nw9.PNG
  Nuclear Weapons Analysis/Model/README.md
  Nuclear Weapons Analysis/Model/nuclear-weapons-analysis-and-classification.ipynb
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___14_0.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___16_1.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___16_3.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___17_0.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___22_1.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___24_1.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___24_3.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___25_0.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___30_1.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___32_0.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___32_1.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___33_0.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___37_0.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___39_0.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___41_0.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___43_0.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___5_0.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___6_1.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___8_1.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___8_3.png
  Nuclear Weapons Analysis/Results-Csv/__results___files/__results___9_0.png
  Nuclear Weapons Analysis/Results-Csv/dt_predictions.csv
  Nuclear Weapons Analysis/Results-Csv/gb_predictions.csv
  Nuclear Weapons Analysis/Results-Csv/knn_predictions.csv
  Nuclear Weapons Analysis/Results-Csv/lr_predictions.csv
  Nuclear Weapons Analysis/Results-Csv/mlp_predictions.csv
  Nuclear Weapons Analysis/Results-Csv/rf_predictions.csv
  Nuclear Weapons Analysis/Results-Csv/svm_predictions.csv
  Nuclear Weapons Analysis/requirements.txt
Labels: Approved :white_check_mark:, KWOC 2023

#489 Gender Recognition By Voice Model
  Gender Recognition By Voice/Dataset/Male and female Voice data creat by al arman ovi .csv
  Gender Recognition By Voice/Dataset/README.md
  Gender Recognition By Voice/Images/1.png
  Gender Recognition By Voice/Images/2.png
  Gender Recognition By Voice/Images/3.png
  Gender Recognition By Voice/Images/4.png
  Gender Recognition By Voice/Images/5.png
  Gender Recognition By Voice/Models/Gender_Recognition_By_Voice.ipynb
  Gender Recognition By Voice/README.md
  Gender Recognition By Voice/requirements.txt
Labels: Approved :white_check_mark:, KWOC 2023

#524 Blood donation analysis
  Blood Donation Prediction/Model/blood_donation_prediction.ipynb
  Blood Donation Prediction/README.md
  Blood Donation Prediction/dataset/tranfusion.zip
  Blood Donation Prediction/dataset/transfusion.csv
  Blood Donation Prediction/images/Screenshot 2024-01-15 142818.png
  Blood Donation Prediction/images/Screenshot 2024-01-15 142844.png
  Blood Donation Prediction/images/Screenshot 2024-01-15 142854.png
  Blood Donation Prediction/images/Screenshot 2024-01-15 142908.png
  Blood Donation Prediction/images/Screenshot 2024-01-15 142921.png
  Blood Donation Prediction/images/Screenshot 2024-01-15 142928.png
  Blood Donation Prediction/images/Screenshot 2024-01-15 142938.png
  Blood Donation Prediction/images/Screenshot 2024-01-15 142944.png
  Blood Donation Prediction/images/Screenshot 2024-01-15 142953.png
  Blood Donation Prediction/images/Screenshot 2024-01-15 143006.png
  Blood Donation Prediction/images/Screenshot 2024-01-15 143017.png
  Blood Donation Prediction/images/Screenshot 2024-01-15 143027.png
Labels: Approved :white_check_mark:, Medium, IWOC2024

#523 House Rent Analysis and Prediction of Mumbai #444
  House rent analysis and prediction of Mumbai/Dataset/house_rent_mumbai.csv
  House rent analysis and prediction of Mumbai/Images/Screenshot 2024-01-14 203212.png
  House rent analysis and prediction of Mumbai/Images/Screenshot 2024-01-14 203348.png
  House rent analysis and prediction of Mumbai/Images/Screenshot 2024-01-15 154053.png
  House rent analysis and prediction of Mumbai/Images/Screenshot 2024-01-15 154155.png
  House rent analysis and prediction of Mumbai/Images/boxplot for area.png
  House rent analysis and prediction of Mumbai/Images/boxplot for price.png
  House rent analysis and prediction of Mumbai/Images/boxplot for size.png
  House rent analysis and prediction of Mumbai/Images/scores of model.png
  House rent analysis and prediction of Mumbai/Model/House_Rent _Analysis_and_Prediction_of_Mumbai.ipynb
  House rent analysis and prediction of Mumbai/Model/ReadMe.MD
  House rent analysis and prediction of Mumbai/requirements.txt
Labels: Approved :white_check_mark:, Medium, IWOC2024

#529 VEHICLE LIVE RISK PREDICTION
  Vehicle Live Risk Prediction/Dataset/Vehicle Risk Prediction Dataset.csv
  Vehicle Live Risk Prediction/Images/1.png
  Vehicle Live Risk Prediction/Images/2.png
  Vehicle Live Risk Prediction/Images/3.png
  Vehicle Live Risk Prediction/Images/boxplot_Fatigue_Level.png
  Vehicle Live Risk Prediction/Images/boxplot_Landscape.png
  Vehicle Live Risk Prediction/Images/boxplot_Light_Conditions.png
  Vehicle Live Risk Prediction/Images/boxplot_Medical_Condition.png
  Vehicle Live Risk Prediction/Images/boxplot_Road_Hazards.png
  Vehicle Live Risk Prediction/Images/boxplot_Road_Surface_Conditions.png
  Vehicle Live Risk Prediction/Images/boxplot_Road_Type.png
  Vehicle Live Risk Prediction/Images/boxplot_Speeding.png
  Vehicle Live Risk Prediction/Images/boxplot_Time_of_Day.png
  Vehicle Live Risk Prediction/Images/boxplot_Traffic_Density.png
  Vehicle Live Risk Prediction/Images/boxplot_Visibility.png
  Vehicle Live Risk Prediction/Images/boxplot_Weather.png
  Vehicle Live Risk Prediction/Images/violinplot_Fatigue_Level.png
  Vehicle Live Risk Prediction/Images/violinplot_Landscape.png
  Vehicle Live Risk Prediction/Images/violinplot_Light_Conditions.png
  Vehicle Live Risk Prediction/Images/violinplot_Medical_Condition.png
  Vehicle Live Risk Prediction/Images/violinplot_Road_Hazards.png
  Vehicle Live Risk Prediction/Images/violinplot_Road_Surface_Conditions.png
  Vehicle Live Risk Prediction/Images/violinplot_Road_Type.png
  Vehicle Live Risk Prediction/Images/violinplot_Speeding.png
  Vehicle Live Risk Prediction/Images/violinplot_Time_of_Day.png
  Vehicle Live Risk Prediction/Images/violinplot_Traffic_Density.png
  Vehicle Live Risk Prediction/Images/violinplot_Visibility.png
  Vehicle Live Risk Prediction/Images/violinplot_Weather.png
  Vehicle Live Risk Prediction/Model/ANN_Based.ipynb
  Vehicle Live Risk Prediction/Model/Dtree1_with_EDA.ipynb
  Vehicle Live Risk Prediction/Model/Extra_Models.ipynb
  Vehicle Live Risk Prediction/Model/MultivariateLogistic.ipynb
  Vehicle Live Risk Prediction/Model/RandomForest.ipynb
  Vehicle Live Risk Prediction/Model/Xgboost.ipynb
  Vehicle Live Risk Prediction/README.md
  Vehicle Live Risk Prediction/requirements.txt
Labels: Approved :white_check_mark:, Hard, JWOC

#533 Most Sold Books in the World Analysis
  Most Sold Books in the World Analysis/Dataset/Books.csv
  Most Sold Books in the World Analysis/Images/Authors with Multiple Bestsellers.png
  Most Sold Books in the World Analysis/Images/Bestsellers in English.png
  Most Sold Books in the World Analysis/Images/Distribution of Languages in the Dataset.png
  Most Sold Books in the World Analysis/Images/Number of Bestsellers per Century.png
  Most Sold Books in the World Analysis/Images/Number of Most Sold Books in Each Language.png
  Most Sold Books in the World Analysis/Images/Top 10 Books by Sales.png
  Most Sold Books in the World Analysis/Images/Top Sold Non-English Books.png
  Most Sold Books in the World Analysis/Images/Word Cloud for Book Genres.png
  Most Sold Books in the World Analysis/Model/Most Sold Books In the World Analysis.ipynb
  Most Sold Books in the World Analysis/Model/README.md
Labels: Approved :white_check_mark:, Medium, JWOC

#534 Bank Negara Indonesia Stock Prediction
  Bank Negara Indonesia Stock Prediction/Dataset/BBNI.JK.csv
  Bank Negara Indonesia Stock Prediction/Images/bar graph of the dataset.png
  Bank Negara Indonesia Stock Prediction/Images/closevsopen.png
  Bank Negara Indonesia Stock Prediction/Images/histogram of the dataset.png
  Bank Negara Indonesia Stock Prediction/Images/stock.png
  Bank Negara Indonesia Stock Prediction/Model/Bank Negara Indonesia Stock Prediction.ipynb
  Bank Negara Indonesia Stock Prediction/README.md
  Bank Negara Indonesia Stock Prediction/requirements.txt
Labels: Approved :white_check_mark:, Ready To Merge :rocket:, Medium, JWOC

#539 Nurse Stress Prediction
  Nurse Stress Prediction/Dataset/README.md
  Nurse Stress Prediction/Images/EDA_plot.jpg
  Nurse Stress Prediction/Images/HR_plot.jpg
  Nurse Stress Prediction/Images/MSE_plot.png
  Nurse Stress Prediction/Images/TEMP_plot.jpg
  Nurse Stress Prediction/Images/X_plot.jpg
  Nurse Stress Prediction/Images/actual_vs_prediction.png
  Nurse Stress Prediction/Images/correlation_heatmap.jpg
  Nurse Stress Prediction/Images/label_plot.jpg
  Nurse Stress Prediction/Images/pca.jpg
  Nurse Stress Prediction/Images/prediction_plot.png
  Nurse Stress Prediction/Models/nurse_stress_prediction.ipynb
  Nurse Stress Prediction/README.md
  Nurse Stress Prediction/requirements.txt
Labels: Approved :white_check_mark:, Hard, IWOC2024

#542 Student Attendance based on Weather Conditions
  Student Attendance based on Weather Conditions/README.MD
  Student Attendance based on Weather Conditions/dataset/.ipynb_checkpoints/student_attendance-checkpoint.csv
  Student Attendance based on Weather Conditions/dataset/student_attendance.csv
  Student Attendance based on Weather Conditions/images/Student Attendance on different Temperature.png
  Student Attendance based on Weather Conditions/images/Student Attendance on different Weather Conditions.png
  Student Attendance based on Weather Conditions/images/Student Attendance.png
  Student Attendance based on Weather Conditions/images/Temperature Distribution.png
  Student Attendance based on Weather Conditions/images/Weather Distribution.png
  Student Attendance based on Weather Conditions/model/.ipynb_checkpoints/Untitled-checkpoint.ipynb
  Student Attendance based on Weather Conditions/model/.ipynb_checkpoints/model-checkpoint.ipynb
  Student Attendance based on Weather Conditions/model/model.ipynb
  Student Attendance based on Weather Conditions/requirements.txt
Labels: Approved :white_check_mark:, Hard, JWOC

#547 Cassava Leaf Disease Classification
  Cassava Leaf Disease Classification/Dataset/README.md
  Cassava Leaf Disease Classification/Images/1.png
  Cassava Leaf Disease Classification/Images/2.png
  Cassava Leaf Disease Classification/Images/Example.png
  Cassava Leaf Disease Classification/Images/Plot.png
  Cassava Leaf Disease Classification/Model/CNN (1).ipynb
  Cassava Leaf Disease Classification/Model/Misc_Models.ipynb
  Cassava Leaf Disease Classification/Model/UnderSampled.ipynb
  Cassava Leaf Disease Classification/README.md
  Cassava Leaf Disease Classification/requirements.txt
Labels: Approved :white_check_mark:, Hard, JWOC

#552 Customer Personality Analysis
  Customer Personality Analysis/Dataset/marketing_campaign.csv
  Customer Personality Analysis/Images/Images.png
  Customer Personality Analysis/Images/expenses.png
  Customer Personality Analysis/Images/figure.png
  Customer Personality Analysis/Images/figure1.png
  Customer Personality Analysis/Images/histplot.png
  Customer Personality Analysis/Images/marital_status.png
  Customer Personality Analysis/Model/Customer personality Analysis.ipynb
  Customer Personality Analysis/README.md
  Customer Personality Analysis/requirements.txt
Labels: Approved :white_check_mark:, Medium, JWOC

#554 Global Retailers Analysis
  Global Retailers Analysis/Dataset/cos2017.csv
  Global Retailers Analysis/Dataset/cos2018.csv
  Global Retailers Analysis/Dataset/cos2019.csv
  Global Retailers Analysis/Images/Choropleth map - Retail revenue by country.png
  Global Retailers Analysis/Images/Distribution of Retail Revenue by Operational Format.png
  Global Retailers Analysis/Images/Dominant Operational Formats Distribution.png
  Global Retailers Analysis/Images/Radar Chart - Operational Format Performance Across Countries.png
  Global Retailers Analysis/Images/Retail Revenue CAGR Over Time.png
  Global Retailers Analysis/Images/Retail Revenue by Country.png
  Global Retailers Analysis/Images/Retail Revenue vs Net Income by Country.png
  Global Retailers Analysis/Images/Retail Revenue vs Parent Company Revenue.png
  Global Retailers Analysis/Images/Sunburst Chart - Retail Revenue Hierarchy.png
  Global Retailers Analysis/Images/Top 10 Retailers by Revenue.png
  Global Retailers Analysis/Images/Treemap - Countries of Operation by Retail Revenue with Improved Hover Information.png
  Global Retailers Analysis/Model/Global_Retailers_Analysis.ipynb
  Global Retailers Analysis/Model/README.md
Labels: Approved :white_check_mark:, Medium, JWOC

#556 Replit Bounties Dataset Analysis
  Replit Bounties Dataset Analysis/Dataset/replit_bounties.csv
  Replit Bounties Dataset Analysis/Images/Bounty_histogram.png
  Replit Bounties Dataset Analysis/Images/Time_bar_plot.png
  Replit Bounties Dataset Analysis/Images/bounty_company_bar.png
  Replit Bounties Dataset Analysis/Images/corr_heatmap.png
  Replit Bounties Dataset Analysis/Images/decision_tree.svg.svg
  Replit Bounties Dataset Analysis/Images/missingno_matrix.png
  Replit Bounties Dataset Analysis/Images/pairplot.png
  Replit Bounties Dataset Analysis/Model/README.md
  Replit Bounties Dataset Analysis/Model/Replit_Bounties_Dataset_Analysis.ipynb
  Replit Bounties Dataset Analysis/requirements.txt
Labels: Approved :white_check_mark:, Medium, JWOC

#557 GOOGLE DEVICES Q AND A ANALYSIS
  Google Devices Q and A Analysis/Dataset/All About Google Devices - Sheet1.csv
  Google Devices Q and A Analysis/Images/1.png
  Google Devices Q and A Analysis/Images/2.png
  Google Devices Q and A Analysis/Images/3.png
  Google Devices Q and A Analysis/Images/4.png
  Google Devices Q and A Analysis/Model/GoogleQ_Aipynb.ipynb
  Google Devices Q and A Analysis/README.md
  Google Devices Q and A Analysis/requirements.txt
Labels: Approved :white_check_mark:, Medium, JWOC

#558 WebMD Drug Review
  WebMD Drug Review/Dataset/dataset.md
  WebMD Drug Review/Images/count.png
  WebMD Drug Review/Images/dataplot.png
  WebMD Drug Review/Images/effectiveness.png
  WebMD Drug Review/Images/effectiveness2.png
  WebMD Drug Review/Images/heatmap.png
  WebMD Drug Review/Images/hist and boxplot.png
  WebMD Drug Review/Images/plot.png
  WebMD Drug Review/Images/satis.png
  WebMD Drug Review/Model/WebMD Drug Review.ipynb
  WebMD Drug Review/README.md
  WebMD Drug Review/requirements.txt
Labels: Approved :white_check_mark:, Medium, IWOC2024

#559 Gapminder Colon Cancer
  Gapminder Colon Cancer/Dataset/Colon Rectum cancer deaths per 100 000 men.csv
  Gapminder Colon Cancer/Images/1955.png
  Gapminder Colon Cancer/Images/2000.png
  Gapminder Colon Cancer/Images/boxplot.png
  Gapminder Colon Cancer/Images/country.png
  Gapminder Colon Cancer/Images/country2.png
  Gapminder Colon Cancer/Images/dataplot.png
  Gapminder Colon Cancer/Images/heatmap.png
  Gapminder Colon Cancer/Images/pie.png
  Gapminder Colon Cancer/Images/pie2.png
  Gapminder Colon Cancer/Model/.ipynb_checkpoints/Gapminder Colon Cancer-checkpoint.ipynb
  Gapminder Colon Cancer/Model/Gapminder Colon Cancer.ipynb
  Gapminder Colon Cancer/README.md
  Gapminder Colon Cancer/requirements.txt
Labels: Approved :white_check_mark:, Points Added :tada:, Medium, JWOC
