Repository abhisheks008/ML-Crate, pull requests merged in 2024-07, with the labels that each got.

#687 Google Analytics Capstone Project
  Google Analytics Capstone Project/Dataset/GCapstone.csv
  Google Analytics Capstone Project/Dataset/README.md
  Google Analytics Capstone Project/Images/download (1).png
  Google Analytics Capstone Project/Images/download (2).png
  Google Analytics Capstone Project/Images/download (3).png
  Google Analytics Capstone Project/Images/download (4).png
  Google Analytics Capstone Project/Images/download (5).png
  Google Analytics Capstone Project/Images/download (6).png
  Google Analytics Capstone Project/Model/Google_Analytics_Capstone_Project.ipynb
  Google Analytics Capstone Project/Model/README.md
  Google Analytics Capstone Project/requirements.txt
Labels: Approved :white_check_mark:, Intermediate, SSOC

#694 Rsna lumbar spine detection
  RSNA Lumbar Spine Degenerative Classification/Dataset/README.md
  RSNA Lumbar Spine Degenerative Classification/Images/__results___107_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___115_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___119_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___12_1.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___13_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___15_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___15_1.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___15_2.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___15_3.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___15_4.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___17_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___19_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___25_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___26_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___27_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___27_1.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___27_2.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___28_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___29_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___29_1.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___29_2.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___33_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___34_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___34_1.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___38_1.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___39_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___40_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___40_1.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___40_2.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___40_3.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___40_4.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___40_5.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___40_6.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___40_7.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___40_8.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___45_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___48_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___49_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___50_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___51_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___67_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___75_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___83_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___91_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___99_0.png
  RSNA Lumbar Spine Degenerative Classification/Images/__results___9_0.png
  RSNA Lumbar Spine Degenerative Classification/Models/README.md
  RSNA Lumbar Spine Degenerative Classification/README.md
  RSNA Lumbar Spine Degenerative Classification/requirements.txt
  RSNA Lumbar Spine Degenerative Classification/results/ada_submission.csv
  RSNA Lumbar Spine Degenerative Classification/results/cat_submission.csv
  RSNA Lumbar Spine Degenerative Classification/results/gb_submission.csv
  RSNA Lumbar Spine Degenerative Classification/results/lgb_submission.csv
  RSNA Lumbar Spine Degenerative Classification/results/logistic_submission.csv
  RSNA Lumbar Spine Degenerative Classification/results/rf_submission.csv
  RSNA Lumbar Spine Degenerative Classification/results/xgb_submission.csv
Labels: Approved :white_check_mark:, HARD, VSOC

#699 Bank credit analysis
  Bank Credit Analysis/Dataset/bank.csv
  Bank Credit Analysis/Images/__results___10_0.png
  Bank Credit Analysis/Images/__results___11_1.png
  Bank Credit Analysis/Images/__results___12_1.png
  Bank Credit Analysis/Images/__results___13_0.png
  Bank Credit Analysis/Images/__results___13_1.png
  Bank Credit Analysis/Images/__results___14_0.png
  Bank Credit Analysis/Images/__results___15_0.png
  Bank Credit Analysis/Images/__results___18_0.png
  Bank Credit Analysis/Images/__results___24_1.png
  Bank Credit Analysis/Images/__results___25_1.png
  Bank Credit Analysis/Images/__results___27_0.png
  Bank Credit Analysis/Images/__results___28_0.png
  Bank Credit Analysis/Images/__results___29_0.png
  Bank Credit Analysis/Images/__results___30_0.png
  Bank Credit Analysis/Images/__results___31_0.png
  Bank Credit Analysis/Model/README.md
  Bank Credit Analysis/Model/bank-credit-analysis.ipynb
  Bank Credit Analysis/README.md
  Bank Credit Analysis/Results/models_results.csv
  Bank Credit Analysis/requirements.txt
Labels: Approved :white_check_mark:, Advanced, SSOC

#708 CVD Dataset Analysis
  CVD Dataset Analysis/Dataset/Balanced_Dataset_Modif.csv
  CVD Dataset Analysis/Dataset/README.md
  CVD Dataset Analysis/Images/correlation_matrix.png
  CVD Dataset Analysis/Images/results.png
  CVD Dataset Analysis/Images/target_class_counts.png
  CVD Dataset Analysis/Images/top5_neg_features.png
  CVD Dataset Analysis/Images/top5_pos_features.png
  CVD Dataset Analysis/Images/univariate_analysis.png
  CVD Dataset Analysis/Model/README.md
  CVD Dataset Analysis/Model/cardiovascular-disease-cvd-dataset-analysis.ipynb
  CVD Dataset Analysis/requirements.txt
Labels: Approved :white_check_mark:, MEDIUM, VSOC

#704 Loan Repayment Prediction Project
  Loan Repayment Prediction/Datasets/test.csv
  Loan Repayment Prediction/Datasets/train.csv
  Loan Repayment Prediction/Images/Comparison Between Genders in Getting the Loan.png
  Loan Repayment Prediction/Images/Comparison between Education Status of an Individual in getting the Loan.png
  Loan Repayment Prediction/Images/Comparison between Married Status in getting the Loan.png
  Loan Repayment Prediction/Images/Comparison between Property Area for getting the Loan.png
  Loan Repayment Prediction/Images/Comparison between Self-Employed or Not in getting the Loan.png
  Loan Repayment Prediction/Images/Correlation Matrix.png
  Loan Repayment Prediction/Model/Loan Repayment Prediction.ipynb
  Loan Repayment Prediction/README.md
  Loan Repayment Prediction/requirements.txt
Labels: Approved :white_check_mark:, Intermediate, SSOC

#712 Sepsis survival prediction
  Sepsis Survival Prediction/Dataset/s41598-020-73558-3_sepsis_survival_primary_cohort.csv
  Sepsis Survival Prediction/Dataset/s41598-020-73558-3_sepsis_survival_study_cohort.csv
  Sepsis Survival Prediction/Dataset/s41598-020-73558-3_sepsis_survival_validation_cohort.csv
  Sepsis Survival Prediction/Images/__results___10_0.png
  Sepsis Survival Prediction/Images/__results___11_1.png
  Sepsis Survival Prediction/Images/__results___11_3.png
  Sepsis Survival Prediction/Images/__results___11_5.png
  Sepsis Survival Prediction/Images/__results___11_7.png
  Sepsis Survival Prediction/Images/__results___12_1.png
  Sepsis Survival Prediction/Images/__results___13_1.png
  Sepsis Survival Prediction/Images/__results___14_2.png
  Sepsis Survival Prediction/Images/__results___15_2.png
  Sepsis Survival Prediction/Images/__results___20_1.png
  Sepsis Survival Prediction/Images/__results___20_11.png
  Sepsis Survival Prediction/Images/__results___20_13.png
  Sepsis Survival Prediction/Images/__results___20_15.png
  Sepsis Survival Prediction/Images/__results___20_17.png
  Sepsis Survival Prediction/Images/__results___20_19.png
  Sepsis Survival Prediction/Images/__results___20_3.png
  Sepsis Survival Prediction/Images/__results___20_5.png
  Sepsis Survival Prediction/Images/__results___20_7.png
  Sepsis Survival Prediction/Images/__results___20_9.png
  Sepsis Survival Prediction/Images/__results___21_0.png
  Sepsis Survival Prediction/Images/__results___21_1.png
  Sepsis Survival Prediction/Images/__results___9_0.png
  Sepsis Survival Prediction/Model/README.md
  Sepsis Survival Prediction/Model/sepsis-fatality-prediction-eda-and-models.ipynb
  Sepsis Survival Prediction/README.md
  Sepsis Survival Prediction/Results/confusion_matrix_AdaBoost.png
  Sepsis Survival Prediction/Results/confusion_matrix_CatBoost.png
  Sepsis Survival Prediction/Results/confusion_matrix_Decision_Tree.png
  Sepsis Survival Prediction/Results/confusion_matrix_Extra_Trees.png
  Sepsis Survival Prediction/Results/confusion_matrix_Gradient_Boosting.png
  Sepsis Survival Prediction/Results/confusion_matrix_LightGBM.png
  Sepsis Survival Prediction/Results/confusion_matrix_Logistic_Regression.png
  Sepsis Survival Prediction/Results/confusion_matrix_Random_Forest.png
  Sepsis Survival Prediction/Results/confusion_matrix_XGBoost.png
  Sepsis Survival Prediction/Results/confusion_matrix_k-NN.png
  Sepsis Survival Prediction/Results/model_accuracy_comparison.png
  Sepsis Survival Prediction/Results/model_accuracy_results.csv
  Sepsis Survival Prediction/requirements.txt
Labels: Approved :white_check_mark:, MEDIUM, VSoC’24

#721 Fictional character battle
  Fictional Character Battle Outcome Prediction/Dataset/fictional_character_battles_complex.csv
  Fictional Character Battle Outcome Prediction/Images/__results___13_0.png
  Fictional Character Battle Outcome Prediction/Images/__results___14_0.png
  Fictional Character Battle Outcome Prediction/Images/__results___15_1.png
  Fictional Character Battle Outcome Prediction/Images/__results___15_3.png
  Fictional Character Battle Outcome Prediction/Images/__results___15_5.png
  Fictional Character Battle Outcome Prediction/Images/__results___16_1.png
  Fictional Character Battle Outcome Prediction/Images/__results___17_0.png
  Fictional Character Battle Outcome Prediction/Images/__results___18_0.png
  Fictional Character Battle Outcome Prediction/Images/__results___19_0.png
  Fictional Character Battle Outcome Prediction/Images/__results___20_0.png
  Fictional Character Battle Outcome Prediction/Images/__results___21_0.png
  Fictional Character Battle Outcome Prediction/Images/__results___25_0.png
  Fictional Character Battle Outcome Prediction/Images/__results___25_1.png
  Fictional Character Battle Outcome Prediction/Images/__results___25_10.png
  Fictional Character Battle Outcome Prediction/Images/__results___25_11.png
  Fictional Character Battle Outcome Prediction/Images/__results___25_2.png
  Fictional Character Battle Outcome Prediction/Images/__results___25_3.png
  Fictional Character Battle Outcome Prediction/Images/__results___25_4.png
  Fictional Character Battle Outcome Prediction/Images/__results___25_5.png
  Fictional Character Battle Outcome Prediction/Images/__results___25_6.png
  Fictional Character Battle Outcome Prediction/Images/__results___25_8.png
  Fictional Character Battle Outcome Prediction/Images/__results___25_9.png
  Fictional Character Battle Outcome Prediction/Images/__results___30_0.png
  Fictional Character Battle Outcome Prediction/Images/__results___31_0.png
  Fictional Character Battle Outcome Prediction/Models/README.md
  Fictional Character Battle Outcome Prediction/Models/fictional-character-battle-outcome.ipynb
  Fictional Character Battle Outcome Prediction/README.md
  Fictional Character Battle Outcome Prediction/Results/evaluation_results.csv
  Fictional Character Battle Outcome Prediction/Results/evaluation_results_with_stacking.csv
  Fictional Character Battle Outcome Prediction/requirements.txt
Labels: Approved :white_check_mark:, Advanced, SSOC

#724 Asthma disease
  Asthma Disease Detection/Dataset/asthma_disease_data.csv
  Asthma Disease Detection/Images/__results___10_1.png
  Asthma Disease Detection/Images/__results___11_1.png
  Asthma Disease Detection/Images/__results___12_1.png
  Asthma Disease Detection/Images/__results___13_1.png
  Asthma Disease Detection/Images/__results___14_1.png
  Asthma Disease Detection/Images/__results___15_1.png
  Asthma Disease Detection/Images/__results___16_2.png
  Asthma Disease Detection/Images/__results___17_1.png
  Asthma Disease Detection/Images/__results___18_0.png
  Asthma Disease Detection/Images/__results___23_10.png
  Asthma Disease Detection/Images/__results___23_12.png
  Asthma Disease Detection/Images/__results___23_14.png
  Asthma Disease Detection/Images/__results___23_16.png
  Asthma Disease Detection/Images/__results___23_18.png
  Asthma Disease Detection/Images/__results___23_2.png
  Asthma Disease Detection/Images/__results___23_20.png
  Asthma Disease Detection/Images/__results___23_22.png
  Asthma Disease Detection/Images/__results___23_24.png
  Asthma Disease Detection/Images/__results___23_26.png
  Asthma Disease Detection/Images/__results___23_28.png
  Asthma Disease Detection/Images/__results___23_4.png
  Asthma Disease Detection/Images/__results___23_6.png
  Asthma Disease Detection/Images/__results___23_8.png
  Asthma Disease Detection/Images/__results___24_0.png
  Asthma Disease Detection/Images/__results___5_1.png
  Asthma Disease Detection/Images/__results___6_0.png
  Asthma Disease Detection/Images/__results___8_2.png
  Asthma Disease Detection/Images/__results___9_1.png
  Asthma Disease Detection/Models/README.md
  Asthma Disease Detection/Models/asthma-disease-detection.ipynb
  Asthma Disease Detection/README.md
  Asthma Disease Detection/Results/confusion_matrix_AdaBoost.png
  Asthma Disease Detection/Results/confusion_matrix_Bagging.png
  Asthma Disease Detection/Results/confusion_matrix_CatBoost.png
  Asthma Disease Detection/Results/confusion_matrix_Decision Tree.png
  Asthma Disease Detection/Results/confusion_matrix_Extra Trees.png
  Asthma Disease Detection/Results/confusion_matrix_Gradient Boosting.png
  Asthma Disease Detection/Results/confusion_matrix_K-Nearest Neighbors.png
  Asthma Disease Detection/Results/confusion_matrix_LightGBM.png
  Asthma Disease Detection/Results/confusion_matrix_Logistic Regression.png
  Asthma Disease Detection/Results/confusion_matrix_Naive Bayes.png
  Asthma Disease Detection/Results/confusion_matrix_Random Forest.png
  Asthma Disease Detection/Results/confusion_matrix_Stacking Classifier.png
  Asthma Disease Detection/Results/confusion_matrix_Support Vector Machine.png
  Asthma Disease Detection/Results/confusion_matrix_XGBoost.png
  Asthma Disease Detection/Results/model_comparison.png
  Asthma Disease Detection/Results/model_results.csv
  Asthma Disease Detection/requirements.txt
Labels: Approved :white_check_mark:, Advanced, SSOC
